// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"fmt"
	"github.com/bionicotaku/lingo-services-profile/internal/infrastructure/configloader"
	"github.com/bionicotaku/lingo-services-profile/internal/repositories"
	"github.com/bionicotaku/lingo-services-profile/internal/tasks/catalog_inbox"
	"github.com/bionicotaku/lingo-utils/gclog"
	"github.com/bionicotaku/lingo-utils/gcpubsub"
	"github.com/bionicotaku/lingo-utils/observability"
	"github.com/bionicotaku/lingo-utils/pgxpoolx"
	"github.com/bionicotaku/lingo-utils/txmanager"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

func wireCatalogInboxTask(contextContext context.Context, params configloader.Params) (*catalogInboxApp, func(), error) {
	runtimeConfig, err := configloader.LoadRuntimeConfig(params)
	if err != nil {
		return nil, nil, err
	}
	observabilityConfig := configloader.ProvideObservabilityConfig(runtimeConfig)
	serviceInfo := configloader.ProvideServiceInfo(runtimeConfig)
	observabilityServiceInfo := configloader.ProvideObservabilityInfo(serviceInfo)
	config := configloader.ProvideLoggerConfig(serviceInfo)
	component, cleanup, err := gclog.NewComponent(config)
	if err != nil {
		return nil, nil, err
	}
	logger := gclog.ProvideLogger(component)
	observabilityComponent, cleanup2, err := observability.NewComponent(contextContext, observabilityConfig, observabilityServiceInfo, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	messagingConfig := configloader.ProvideMessagingConfig(runtimeConfig)
	gcpubsubConfig := configloader.ProvidePubSubConfig(messagingConfig)
	dependencies := configloader.ProvidePubSubDependencies(logger)
	gcpubsubComponent, cleanup3, err := gcpubsub.NewComponent(contextContext, gcpubsubConfig, dependencies)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	subscriber := gcpubsub.ProvideSubscriber(gcpubsubComponent)
	databaseConfig := configloader.ProvideDatabaseConfig(runtimeConfig)
	pgxpoolxConfig := configloader.ProvidePgxConfig(databaseConfig)
	pgxpoolxComponent, cleanup4, err := pgxpoolx.ProvideComponent(contextContext, pgxpoolxConfig, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pool := pgxpoolx.ProvidePool(pgxpoolxComponent)
	configConfig := configloader.ProvideOutboxConfig(messagingConfig)
	inboxRepository := repositories.NewInboxRepository(pool, logger, configConfig)
	profileVideoProjectionRepository := repositories.NewProfileVideoProjectionRepository(pool, logger)
	txmanagerConfig := configloader.ProvideTxConfig(runtimeConfig)
	txmanagerComponent, cleanup5, err := txmanager.NewComponent(txmanagerConfig, pool, logger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	manager := txmanager.ProvideManager(txmanagerComponent)
	task := cataloginbox.ProvideTask(subscriber, inboxRepository, profileVideoProjectionRepository, manager, configConfig, logger)
	mainCatalogInboxApp, err := newCatalogInboxApp(observabilityComponent, logger, task)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return mainCatalogInboxApp, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var catalogInboxRepoSet = wire.NewSet(repositories.NewInboxRepository, repositories.NewProfileVideoProjectionRepository)

func newCatalogInboxApp(_ *observability.Component, logger log.Logger, task *cataloginbox.Task) (*catalogInboxApp, error) {
	if task == nil {
		return &catalogInboxApp{Logger: logger}, nil
	}
	if logger == nil {
		return nil, fmt.Errorf("logger not initialized")
	}
	return &catalogInboxApp{
		Task:   task,
		Logger: logger,
	}, nil
}
