// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/profile/v1/events.proto

package profilev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EngagementAddedEvent 对应 profile.engagement.added。
type EngagementAddedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	FavoriteType  FavoriteType           `protobuf:"varint,4,opt,name=favorite_type,json=favoriteType,proto3,enum=profile.v1.FavoriteType" json:"favorite_type,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Stats         *VideoStats            `protobuf:"bytes,7,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngagementAddedEvent) Reset() {
	*x = EngagementAddedEvent{}
	mi := &file_api_profile_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngagementAddedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngagementAddedEvent) ProtoMessage() {}

func (x *EngagementAddedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngagementAddedEvent.ProtoReflect.Descriptor instead.
func (*EngagementAddedEvent) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *EngagementAddedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EngagementAddedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EngagementAddedEvent) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *EngagementAddedEvent) GetFavoriteType() FavoriteType {
	if x != nil {
		return x.FavoriteType
	}
	return FavoriteType_FAVORITE_TYPE_UNSPECIFIED
}

func (x *EngagementAddedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *EngagementAddedEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EngagementAddedEvent) GetStats() *VideoStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// EngagementRemovedEvent 对应 profile.engagement.removed。
type EngagementRemovedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	FavoriteType  FavoriteType           `protobuf:"varint,4,opt,name=favorite_type,json=favoriteType,proto3,enum=profile.v1.FavoriteType" json:"favorite_type,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Stats         *VideoStats            `protobuf:"bytes,8,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngagementRemovedEvent) Reset() {
	*x = EngagementRemovedEvent{}
	mi := &file_api_profile_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngagementRemovedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngagementRemovedEvent) ProtoMessage() {}

func (x *EngagementRemovedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngagementRemovedEvent.ProtoReflect.Descriptor instead.
func (*EngagementRemovedEvent) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *EngagementRemovedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EngagementRemovedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EngagementRemovedEvent) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *EngagementRemovedEvent) GetFavoriteType() FavoriteType {
	if x != nil {
		return x.FavoriteType
	}
	return FavoriteType_FAVORITE_TYPE_UNSPECIFIED
}

func (x *EngagementRemovedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *EngagementRemovedEvent) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *EngagementRemovedEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EngagementRemovedEvent) GetStats() *VideoStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// WatchProgressedEvent 对应 profile.watch.progressed。
type WatchProgressedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Progress      *WatchProgress         `protobuf:"bytes,4,opt,name=progress,proto3" json:"progress,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchProgressedEvent) Reset() {
	*x = WatchProgressedEvent{}
	mi := &file_api_profile_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchProgressedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProgressedEvent) ProtoMessage() {}

func (x *WatchProgressedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProgressedEvent.ProtoReflect.Descriptor instead.
func (*WatchProgressedEvent) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *WatchProgressedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WatchProgressedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WatchProgressedEvent) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *WatchProgressedEvent) GetProgress() *WatchProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *WatchProgressedEvent) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_api_profile_v1_events_proto protoreflect.FileDescriptor

const file_api_profile_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/profile/v1/events.proto\x12\n" +
	"profile.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1capi/profile/v1/profile.proto\"\xa7\x02\n" +
	"\x14EngagementAddedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\tR\avideoId\x12=\n" +
	"\rfavorite_type\x18\x04 \x01(\x0e2\x18.profile.v1.FavoriteTypeR\ffavoriteType\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12,\n" +
	"\x05stats\x18\a \x01(\v2\x16.profile.v1.VideoStatsR\x05stats\"\xe4\x02\n" +
	"\x16EngagementRemovedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\tR\avideoId\x12=\n" +
	"\rfavorite_type\x18\x04 \x01(\x0e2\x18.profile.v1.FavoriteTypeR\ffavoriteType\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x129\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12,\n" +
	"\x05stats\x18\b \x01(\v2\x16.profile.v1.VideoStatsR\x05stats\"\xcf\x01\n" +
	"\x14WatchProgressedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\tR\avideoId\x125\n" +
	"\bprogress\x18\x04 \x01(\v2\x19.profile.v1.WatchProgressR\bprogress\x121\n" +
	"\acontext\x18\x05 \x01(\v2\x17.google.protobuf.StructR\acontextBHZFgithub.com/bionicotaku/lingo-services-profile/api/profile/v1;profilev1b\x06proto3"

var (
	file_api_profile_v1_events_proto_rawDescOnce sync.Once
	file_api_profile_v1_events_proto_rawDescData []byte
)

func file_api_profile_v1_events_proto_rawDescGZIP() []byte {
	file_api_profile_v1_events_proto_rawDescOnce.Do(func() {
		file_api_profile_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_profile_v1_events_proto_rawDesc), len(file_api_profile_v1_events_proto_rawDesc)))
	})
	return file_api_profile_v1_events_proto_rawDescData
}

var file_api_profile_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_profile_v1_events_proto_goTypes = []any{
	(*EngagementAddedEvent)(nil),   // 0: profile.v1.EngagementAddedEvent
	(*EngagementRemovedEvent)(nil), // 1: profile.v1.EngagementRemovedEvent
	(*WatchProgressedEvent)(nil),   // 2: profile.v1.WatchProgressedEvent
	(FavoriteType)(0),              // 3: profile.v1.FavoriteType
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
	(*VideoStats)(nil),             // 5: profile.v1.VideoStats
	(*WatchProgress)(nil),          // 6: profile.v1.WatchProgress
	(*structpb.Struct)(nil),        // 7: google.protobuf.Struct
}
var file_api_profile_v1_events_proto_depIdxs = []int32{
	3, // 0: profile.v1.EngagementAddedEvent.favorite_type:type_name -> profile.v1.FavoriteType
	4, // 1: profile.v1.EngagementAddedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	5, // 2: profile.v1.EngagementAddedEvent.stats:type_name -> profile.v1.VideoStats
	3, // 3: profile.v1.EngagementRemovedEvent.favorite_type:type_name -> profile.v1.FavoriteType
	4, // 4: profile.v1.EngagementRemovedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	4, // 5: profile.v1.EngagementRemovedEvent.deleted_at:type_name -> google.protobuf.Timestamp
	5, // 6: profile.v1.EngagementRemovedEvent.stats:type_name -> profile.v1.VideoStats
	6, // 7: profile.v1.WatchProgressedEvent.progress:type_name -> profile.v1.WatchProgress
	7, // 8: profile.v1.WatchProgressedEvent.context:type_name -> google.protobuf.Struct
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_api_profile_v1_events_proto_init() }
func file_api_profile_v1_events_proto_init() {
	if File_api_profile_v1_events_proto != nil {
		return
	}
	file_api_profile_v1_profile_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_profile_v1_events_proto_rawDesc), len(file_api_profile_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_profile_v1_events_proto_goTypes,
		DependencyIndexes: file_api_profile_v1_events_proto_depIdxs,
		MessageInfos:      file_api_profile_v1_events_proto_msgTypes,
	}.Build()
	File_api_profile_v1_events_proto = out.File
	file_api_profile_v1_events_proto_goTypes = nil
	file_api_profile_v1_events_proto_depIdxs = nil
}
