// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/profile/v1/profile.proto

package profilev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FavoriteAction 表示收藏/点赞操作类型。
type FavoriteAction int32

const (
	FavoriteAction_FAVORITE_ACTION_UNSPECIFIED FavoriteAction = 0
	FavoriteAction_FAVORITE_ACTION_ADD         FavoriteAction = 1
	FavoriteAction_FAVORITE_ACTION_REMOVE      FavoriteAction = 2
)

// Enum value maps for FavoriteAction.
var (
	FavoriteAction_name = map[int32]string{
		0: "FAVORITE_ACTION_UNSPECIFIED",
		1: "FAVORITE_ACTION_ADD",
		2: "FAVORITE_ACTION_REMOVE",
	}
	FavoriteAction_value = map[string]int32{
		"FAVORITE_ACTION_UNSPECIFIED": 0,
		"FAVORITE_ACTION_ADD":         1,
		"FAVORITE_ACTION_REMOVE":      2,
	}
)

func (x FavoriteAction) Enum() *FavoriteAction {
	p := new(FavoriteAction)
	*p = x
	return p
}

func (x FavoriteAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FavoriteAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_profile_v1_profile_proto_enumTypes[0].Descriptor()
}

func (FavoriteAction) Type() protoreflect.EnumType {
	return &file_api_profile_v1_profile_proto_enumTypes[0]
}

func (x FavoriteAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FavoriteAction.Descriptor instead.
func (FavoriteAction) EnumDescriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{0}
}

// FavoriteType 表示互动类别。
type FavoriteType int32

const (
	FavoriteType_FAVORITE_TYPE_UNSPECIFIED FavoriteType = 0
	FavoriteType_FAVORITE_TYPE_LIKE        FavoriteType = 1
	FavoriteType_FAVORITE_TYPE_BOOKMARK    FavoriteType = 2
)

// Enum value maps for FavoriteType.
var (
	FavoriteType_name = map[int32]string{
		0: "FAVORITE_TYPE_UNSPECIFIED",
		1: "FAVORITE_TYPE_LIKE",
		2: "FAVORITE_TYPE_BOOKMARK",
	}
	FavoriteType_value = map[string]int32{
		"FAVORITE_TYPE_UNSPECIFIED": 0,
		"FAVORITE_TYPE_LIKE":        1,
		"FAVORITE_TYPE_BOOKMARK":    2,
	}
)

func (x FavoriteType) Enum() *FavoriteType {
	p := new(FavoriteType)
	*p = x
	return p
}

func (x FavoriteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FavoriteType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_profile_v1_profile_proto_enumTypes[1].Descriptor()
}

func (FavoriteType) Type() protoreflect.EnumType {
	return &file_api_profile_v1_profile_proto_enumTypes[1]
}

func (x FavoriteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FavoriteType.Descriptor instead.
func (FavoriteType) EnumDescriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{1}
}

// GetProfileRequest 描述档案查询条件。
type GetProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id 为空表示读取当前调用方自身档案；服务身份可指定任意用户。
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// UpdateProfileRequest 更新档案基础信息。
type UpdateProfileRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	UserId  string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Profile *Profile               `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	// update_mask 指定需要更新的字段，例如 display_name, avatar_url。
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// 期望的 profile_version，用于乐观锁控制。
	ExpectedProfileVersion *wrapperspb.Int64Value `protobuf:"bytes,4,opt,name=expected_profile_version,json=expectedProfileVersion,proto3" json:"expected_profile_version,omitempty"`
	// 幂等键，透传 Idempotency-Key header。
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *UpdateProfileRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateProfileRequest) GetExpectedProfileVersion() *wrapperspb.Int64Value {
	if x != nil {
		return x.ExpectedProfileVersion
	}
	return nil
}

func (x *UpdateProfileRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// UpdatePreferencesRequest 局部更新偏好字段。
type UpdatePreferencesRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	UserId                 string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Preferences            *Preferences           `protobuf:"bytes,2,opt,name=preferences,proto3" json:"preferences,omitempty"`
	UpdateMask             *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	ExpectedProfileVersion *wrapperspb.Int64Value `protobuf:"bytes,4,opt,name=expected_profile_version,json=expectedProfileVersion,proto3" json:"expected_profile_version,omitempty"`
	IdempotencyKey         string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetPreferences() *Preferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *UpdatePreferencesRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdatePreferencesRequest) GetExpectedProfileVersion() *wrapperspb.Int64Value {
	if x != nil {
		return x.ExpectedProfileVersion
	}
	return nil
}

func (x *UpdatePreferencesRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type UpdatePreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesResponse) Reset() {
	*x = UpdatePreferencesResponse{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesResponse) ProtoMessage() {}

func (x *UpdatePreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesResponse) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePreferencesResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// MutateFavoriteRequest 执行收藏/点赞写操作。
type MutateFavoriteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId        string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	FavoriteType   FavoriteType           `protobuf:"varint,3,opt,name=favorite_type,json=favoriteType,proto3,enum=profile.v1.FavoriteType" json:"favorite_type,omitempty"`
	Action         FavoriteAction         `protobuf:"varint,4,opt,name=action,proto3,enum=profile.v1.FavoriteAction" json:"action,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MutateFavoriteRequest) Reset() {
	*x = MutateFavoriteRequest{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateFavoriteRequest) ProtoMessage() {}

func (x *MutateFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateFavoriteRequest.ProtoReflect.Descriptor instead.
func (*MutateFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{6}
}

func (x *MutateFavoriteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MutateFavoriteRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *MutateFavoriteRequest) GetFavoriteType() FavoriteType {
	if x != nil {
		return x.FavoriteType
	}
	return FavoriteType_FAVORITE_TYPE_UNSPECIFIED
}

func (x *MutateFavoriteRequest) GetAction() FavoriteAction {
	if x != nil {
		return x.Action
	}
	return FavoriteAction_FAVORITE_ACTION_UNSPECIFIED
}

func (x *MutateFavoriteRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *MutateFavoriteRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type MutateFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *FavoriteState         `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Stats         *VideoStats            `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateFavoriteResponse) Reset() {
	*x = MutateFavoriteResponse{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateFavoriteResponse) ProtoMessage() {}

func (x *MutateFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateFavoriteResponse.ProtoReflect.Descriptor instead.
func (*MutateFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{7}
}

func (x *MutateFavoriteResponse) GetState() *FavoriteState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *MutateFavoriteResponse) GetStats() *VideoStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// BatchQueryFavoriteRequest 批量查询收藏/点赞状态。
type BatchQueryFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoIds      []string               `protobuf:"bytes,2,rep,name=video_ids,json=videoIds,proto3" json:"video_ids,omitempty"`
	IncludeStats  bool                   `protobuf:"varint,3,opt,name=include_stats,json=includeStats,proto3" json:"include_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchQueryFavoriteRequest) Reset() {
	*x = BatchQueryFavoriteRequest{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchQueryFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchQueryFavoriteRequest) ProtoMessage() {}

func (x *BatchQueryFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchQueryFavoriteRequest.ProtoReflect.Descriptor instead.
func (*BatchQueryFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{8}
}

func (x *BatchQueryFavoriteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BatchQueryFavoriteRequest) GetVideoIds() []string {
	if x != nil {
		return x.VideoIds
	}
	return nil
}

func (x *BatchQueryFavoriteRequest) GetIncludeStats() bool {
	if x != nil {
		return x.IncludeStats
	}
	return false
}

type BatchQueryFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*FavoriteSummary     `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchQueryFavoriteResponse) Reset() {
	*x = BatchQueryFavoriteResponse{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchQueryFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchQueryFavoriteResponse) ProtoMessage() {}

func (x *BatchQueryFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchQueryFavoriteResponse.ProtoReflect.Descriptor instead.
func (*BatchQueryFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{9}
}

func (x *BatchQueryFavoriteResponse) GetSummaries() []*FavoriteSummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

// ListFavoritesRequest 游标分页收藏列表。
type ListFavoritesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoritesRequest) Reset() {
	*x = ListFavoritesRequest{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoritesRequest) ProtoMessage() {}

func (x *ListFavoritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoritesRequest.ProtoReflect.Descriptor instead.
func (*ListFavoritesRequest) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{10}
}

func (x *ListFavoritesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListFavoritesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFavoritesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListFavoritesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Favorites     []*FavoriteItem        `protobuf:"bytes,1,rep,name=favorites,proto3" json:"favorites,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoritesResponse) Reset() {
	*x = ListFavoritesResponse{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoritesResponse) ProtoMessage() {}

func (x *ListFavoritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoritesResponse.ProtoReflect.Descriptor instead.
func (*ListFavoritesResponse) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{11}
}

func (x *ListFavoritesResponse) GetFavorites() []*FavoriteItem {
	if x != nil {
		return x.Favorites
	}
	return nil
}

func (x *ListFavoritesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// UpsertWatchProgressRequest 写入观看进度。
type UpsertWatchProgressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId        string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Progress       *WatchProgress         `protobuf:"bytes,3,opt,name=progress,proto3" json:"progress,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertWatchProgressRequest) Reset() {
	*x = UpsertWatchProgressRequest{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertWatchProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertWatchProgressRequest) ProtoMessage() {}

func (x *UpsertWatchProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertWatchProgressRequest.ProtoReflect.Descriptor instead.
func (*UpsertWatchProgressRequest) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{12}
}

func (x *UpsertWatchProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertWatchProgressRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *UpsertWatchProgressRequest) GetProgress() *WatchProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *UpsertWatchProgressRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type UpsertWatchProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *WatchProgress         `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	Stats         *VideoStats            `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertWatchProgressResponse) Reset() {
	*x = UpsertWatchProgressResponse{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertWatchProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertWatchProgressResponse) ProtoMessage() {}

func (x *UpsertWatchProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertWatchProgressResponse.ProtoReflect.Descriptor instead.
func (*UpsertWatchProgressResponse) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{13}
}

func (x *UpsertWatchProgressResponse) GetProgress() *WatchProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *UpsertWatchProgressResponse) GetStats() *VideoStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// ListWatchHistoryRequest 返回观看历史。
type ListWatchHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWatchHistoryRequest) Reset() {
	*x = ListWatchHistoryRequest{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWatchHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchHistoryRequest) ProtoMessage() {}

func (x *ListWatchHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListWatchHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{14}
}

func (x *ListWatchHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListWatchHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWatchHistoryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListWatchHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*WatchHistoryEntry   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWatchHistoryResponse) Reset() {
	*x = ListWatchHistoryResponse{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWatchHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchHistoryResponse) ProtoMessage() {}

func (x *ListWatchHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListWatchHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{15}
}

func (x *ListWatchHistoryResponse) GetItems() []*WatchHistoryEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListWatchHistoryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type PurgeUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeUserDataRequest) Reset() {
	*x = PurgeUserDataRequest{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeUserDataRequest) ProtoMessage() {}

func (x *PurgeUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeUserDataRequest.ProtoReflect.Descriptor instead.
func (*PurgeUserDataRequest) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{16}
}

func (x *PurgeUserDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PurgeUserDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// purge_task_id 可用于后台跟踪清理任务。
	PurgeTaskId   string `protobuf:"bytes,1,opt,name=purge_task_id,json=purgeTaskId,proto3" json:"purge_task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeUserDataResponse) Reset() {
	*x = PurgeUserDataResponse{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeUserDataResponse) ProtoMessage() {}

func (x *PurgeUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeUserDataResponse.ProtoReflect.Descriptor instead.
func (*PurgeUserDataResponse) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{17}
}

func (x *PurgeUserDataResponse) GetPurgeTaskId() string {
	if x != nil {
		return x.PurgeTaskId
	}
	return ""
}

// Profile 表示用户档案。
type Profile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName    string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl      string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	ProfileVersion int64                  `protobuf:"varint,4,opt,name=profile_version,json=profileVersion,proto3" json:"profile_version,omitempty"`
	Preferences    *Preferences           `protobuf:"bytes,5,opt,name=preferences,proto3" json:"preferences,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{18}
}

func (x *Profile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Profile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Profile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Profile) GetProfileVersion() int64 {
	if x != nil {
		return x.ProfileVersion
	}
	return 0
}

func (x *Profile) GetPreferences() *Preferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *Profile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Profile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Preferences 表示学习/通知偏好。
type Preferences struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LearningGoal      string                 `protobuf:"bytes,1,opt,name=learning_goal,json=learningGoal,proto3" json:"learning_goal,omitempty"`
	DailyQuotaMinutes *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=daily_quota_minutes,json=dailyQuotaMinutes,proto3" json:"daily_quota_minutes,omitempty"`
	// extra 用于保留未结构化的偏好字段（Post-MVP 扩展）。
	Extra         *structpb.Struct `protobuf:"bytes,99,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preferences) Reset() {
	*x = Preferences{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preferences) ProtoMessage() {}

func (x *Preferences) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preferences.ProtoReflect.Descriptor instead.
func (*Preferences) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{19}
}

func (x *Preferences) GetLearningGoal() string {
	if x != nil {
		return x.LearningGoal
	}
	return ""
}

func (x *Preferences) GetDailyQuotaMinutes() *wrapperspb.Int32Value {
	if x != nil {
		return x.DailyQuotaMinutes
	}
	return nil
}

func (x *Preferences) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

// FavoriteState 表示当前收藏/点赞状态。
type FavoriteState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasLiked      bool                   `protobuf:"varint,1,opt,name=has_liked,json=hasLiked,proto3" json:"has_liked,omitempty"`
	HasBookmarked bool                   `protobuf:"varint,2,opt,name=has_bookmarked,json=hasBookmarked,proto3" json:"has_bookmarked,omitempty"`
	LikedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=liked_at,json=likedAt,proto3" json:"liked_at,omitempty"`
	BookmarkedAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=bookmarked_at,json=bookmarkedAt,proto3" json:"bookmarked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteState) Reset() {
	*x = FavoriteState{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteState) ProtoMessage() {}

func (x *FavoriteState) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteState.ProtoReflect.Descriptor instead.
func (*FavoriteState) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{20}
}

func (x *FavoriteState) GetHasLiked() bool {
	if x != nil {
		return x.HasLiked
	}
	return false
}

func (x *FavoriteState) GetHasBookmarked() bool {
	if x != nil {
		return x.HasBookmarked
	}
	return false
}

func (x *FavoriteState) GetLikedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LikedAt
	}
	return nil
}

func (x *FavoriteState) GetBookmarkedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BookmarkedAt
	}
	return nil
}

// FavoriteItem 表示收藏列表项。
type FavoriteItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	FavoriteType  FavoriteType           `protobuf:"varint,2,opt,name=favorite_type,json=favoriteType,proto3,enum=profile.v1.FavoriteType" json:"favorite_type,omitempty"`
	State         *FavoriteState         `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Video         *VideoMetadata         `protobuf:"bytes,4,opt,name=video,proto3" json:"video,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteItem) Reset() {
	*x = FavoriteItem{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteItem) ProtoMessage() {}

func (x *FavoriteItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteItem.ProtoReflect.Descriptor instead.
func (*FavoriteItem) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{21}
}

func (x *FavoriteItem) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *FavoriteItem) GetFavoriteType() FavoriteType {
	if x != nil {
		return x.FavoriteType
	}
	return FavoriteType_FAVORITE_TYPE_UNSPECIFIED
}

func (x *FavoriteItem) GetState() *FavoriteState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *FavoriteItem) GetVideo() *VideoMetadata {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *FavoriteItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FavoriteItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// FavoriteSummary 表示批量查询结果。
type FavoriteSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	State         *FavoriteState         `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Stats         *VideoStats            `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteSummary) Reset() {
	*x = FavoriteSummary{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteSummary) ProtoMessage() {}

func (x *FavoriteSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteSummary.ProtoReflect.Descriptor instead.
func (*FavoriteSummary) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{22}
}

func (x *FavoriteSummary) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *FavoriteSummary) GetState() *FavoriteState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *FavoriteSummary) GetStats() *VideoStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// WatchProgress 表示观看进度状态。
type WatchProgress struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PositionSeconds   int64                  `protobuf:"varint,1,opt,name=position_seconds,json=positionSeconds,proto3" json:"position_seconds,omitempty"`
	ProgressRatio     float64                `protobuf:"fixed64,2,opt,name=progress_ratio,json=progressRatio,proto3" json:"progress_ratio,omitempty"`
	TotalWatchSeconds int64                  `protobuf:"varint,3,opt,name=total_watch_seconds,json=totalWatchSeconds,proto3" json:"total_watch_seconds,omitempty"`
	FirstWatchedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=first_watched_at,json=firstWatchedAt,proto3" json:"first_watched_at,omitempty"`
	LastWatchedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_watched_at,json=lastWatchedAt,proto3" json:"last_watched_at,omitempty"`
	ExpiresAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SessionId         string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WatchProgress) Reset() {
	*x = WatchProgress{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProgress) ProtoMessage() {}

func (x *WatchProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProgress.ProtoReflect.Descriptor instead.
func (*WatchProgress) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{23}
}

func (x *WatchProgress) GetPositionSeconds() int64 {
	if x != nil {
		return x.PositionSeconds
	}
	return 0
}

func (x *WatchProgress) GetProgressRatio() float64 {
	if x != nil {
		return x.ProgressRatio
	}
	return 0
}

func (x *WatchProgress) GetTotalWatchSeconds() int64 {
	if x != nil {
		return x.TotalWatchSeconds
	}
	return 0
}

func (x *WatchProgress) GetFirstWatchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstWatchedAt
	}
	return nil
}

func (x *WatchProgress) GetLastWatchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastWatchedAt
	}
	return nil
}

func (x *WatchProgress) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *WatchProgress) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// WatchHistoryEntry 表示观看历史记录。
type WatchHistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Progress      *WatchProgress         `protobuf:"bytes,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Video         *VideoMetadata         `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchHistoryEntry) Reset() {
	*x = WatchHistoryEntry{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchHistoryEntry) ProtoMessage() {}

func (x *WatchHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchHistoryEntry.ProtoReflect.Descriptor instead.
func (*WatchHistoryEntry) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{24}
}

func (x *WatchHistoryEntry) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *WatchHistoryEntry) GetProgress() *WatchProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *WatchHistoryEntry) GetVideo() *VideoMetadata {
	if x != nil {
		return x.Video
	}
	return nil
}

// VideoMetadata 从 Catalog 投影来的元数据。
type VideoMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VideoId           string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DurationMicros    int64                  `protobuf:"varint,4,opt,name=duration_micros,json=durationMicros,proto3" json:"duration_micros,omitempty"`
	ThumbnailUrl      string                 `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	HlsMasterPlaylist string                 `protobuf:"bytes,6,opt,name=hls_master_playlist,json=hlsMasterPlaylist,proto3" json:"hls_master_playlist,omitempty"`
	Status            string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	VisibilityStatus  string                 `protobuf:"bytes,8,opt,name=visibility_status,json=visibilityStatus,proto3" json:"visibility_status,omitempty"`
	PublishedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	Version           int64                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VideoMetadata) Reset() {
	*x = VideoMetadata{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMetadata) ProtoMessage() {}

func (x *VideoMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMetadata.ProtoReflect.Descriptor instead.
func (*VideoMetadata) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{25}
}

func (x *VideoMetadata) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoMetadata) GetDurationMicros() int64 {
	if x != nil {
		return x.DurationMicros
	}
	return 0
}

func (x *VideoMetadata) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *VideoMetadata) GetHlsMasterPlaylist() string {
	if x != nil {
		return x.HlsMasterPlaylist
	}
	return ""
}

func (x *VideoMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VideoMetadata) GetVisibilityStatus() string {
	if x != nil {
		return x.VisibilityStatus
	}
	return ""
}

func (x *VideoMetadata) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *VideoMetadata) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VideoMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// VideoStats 表示聚合统计。
type VideoStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LikeCount         int64                  `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	BookmarkCount     int64                  `protobuf:"varint,2,opt,name=bookmark_count,json=bookmarkCount,proto3" json:"bookmark_count,omitempty"`
	UniqueWatchers    int64                  `protobuf:"varint,3,opt,name=unique_watchers,json=uniqueWatchers,proto3" json:"unique_watchers,omitempty"`
	TotalWatchSeconds int64                  `protobuf:"varint,4,opt,name=total_watch_seconds,json=totalWatchSeconds,proto3" json:"total_watch_seconds,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VideoStats) Reset() {
	*x = VideoStats{}
	mi := &file_api_profile_v1_profile_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStats) ProtoMessage() {}

func (x *VideoStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_profile_v1_profile_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStats.ProtoReflect.Descriptor instead.
func (*VideoStats) Descriptor() ([]byte, []int) {
	return file_api_profile_v1_profile_proto_rawDescGZIP(), []int{26}
}

func (x *VideoStats) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *VideoStats) GetBookmarkCount() int64 {
	if x != nil {
		return x.BookmarkCount
	}
	return 0
}

func (x *VideoStats) GetUniqueWatchers() int64 {
	if x != nil {
		return x.UniqueWatchers
	}
	return 0
}

func (x *VideoStats) GetTotalWatchSeconds() int64 {
	if x != nil {
		return x.TotalWatchSeconds
	}
	return 0
}

func (x *VideoStats) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_profile_v1_profile_proto protoreflect.FileDescriptor

const file_api_profile_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x1capi/profile/v1/profile.proto\x12\n" +
	"profile.v1\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"C\n" +
	"\x12GetProfileResponse\x12-\n" +
	"\aprofile\x18\x01 \x01(\v2\x13.profile.v1.ProfileR\aprofile\"\x9b\x02\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12-\n" +
	"\aprofile\x18\x02 \x01(\v2\x13.profile.v1.ProfileR\aprofile\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12U\n" +
	"\x18expected_profile_version\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\x16expectedProfileVersion\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"F\n" +
	"\x15UpdateProfileResponse\x12-\n" +
	"\aprofile\x18\x01 \x01(\v2\x13.profile.v1.ProfileR\aprofile\"\xab\x02\n" +
	"\x18UpdatePreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\vpreferences\x18\x02 \x01(\v2\x17.profile.v1.PreferencesR\vpreferences\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12U\n" +
	"\x18expected_profile_version\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\x16expectedProfileVersion\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"J\n" +
	"\x19UpdatePreferencesResponse\x12-\n" +
	"\aprofile\x18\x01 \x01(\v2\x13.profile.v1.ProfileR\aprofile\"\xa4\x02\n" +
	"\x15MutateFavoriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12=\n" +
	"\rfavorite_type\x18\x03 \x01(\x0e2\x18.profile.v1.FavoriteTypeR\ffavoriteType\x122\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1a.profile.v1.FavoriteActionR\x06action\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"w\n" +
	"\x16MutateFavoriteResponse\x12/\n" +
	"\x05state\x18\x01 \x01(\v2\x19.profile.v1.FavoriteStateR\x05state\x12,\n" +
	"\x05stats\x18\x02 \x01(\v2\x16.profile.v1.VideoStatsR\x05stats\"v\n" +
	"\x19BatchQueryFavoriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tvideo_ids\x18\x02 \x03(\tR\bvideoIds\x12#\n" +
	"\rinclude_stats\x18\x03 \x01(\bR\fincludeStats\"W\n" +
	"\x1aBatchQueryFavoriteResponse\x129\n" +
	"\tsummaries\x18\x01 \x03(\v2\x1b.profile.v1.FavoriteSummaryR\tsummaries\"k\n" +
	"\x14ListFavoritesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"w\n" +
	"\x15ListFavoritesResponse\x126\n" +
	"\tfavorites\x18\x01 \x03(\v2\x18.profile.v1.FavoriteItemR\tfavorites\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xb0\x01\n" +
	"\x1aUpsertWatchProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x125\n" +
	"\bprogress\x18\x03 \x01(\v2\x19.profile.v1.WatchProgressR\bprogress\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"\x82\x01\n" +
	"\x1bUpsertWatchProgressResponse\x125\n" +
	"\bprogress\x18\x01 \x01(\v2\x19.profile.v1.WatchProgressR\bprogress\x12,\n" +
	"\x05stats\x18\x02 \x01(\v2\x16.profile.v1.VideoStatsR\x05stats\"n\n" +
	"\x17ListWatchHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"w\n" +
	"\x18ListWatchHistoryResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.profile.v1.WatchHistoryEntryR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"/\n" +
	"\x14PurgeUserDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x15PurgeUserDataResponse\x12\"\n" +
	"\rpurge_task_id\x18\x01 \x01(\tR\vpurgeTaskId\"\xbe\x02\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12'\n" +
	"\x0fprofile_version\x18\x04 \x01(\x03R\x0eprofileVersion\x129\n" +
	"\vpreferences\x18\x05 \x01(\v2\x17.profile.v1.PreferencesR\vpreferences\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xae\x01\n" +
	"\vPreferences\x12#\n" +
	"\rlearning_goal\x18\x01 \x01(\tR\flearningGoal\x12K\n" +
	"\x13daily_quota_minutes\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x11dailyQuotaMinutes\x12-\n" +
	"\x05extra\x18c \x01(\v2\x17.google.protobuf.StructR\x05extra\"\xcb\x01\n" +
	"\rFavoriteState\x12\x1b\n" +
	"\thas_liked\x18\x01 \x01(\bR\bhasLiked\x12%\n" +
	"\x0ehas_bookmarked\x18\x02 \x01(\bR\rhasBookmarked\x125\n" +
	"\bliked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\alikedAt\x12?\n" +
	"\rbookmarked_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fbookmarkedAt\"\xc0\x02\n" +
	"\fFavoriteItem\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12=\n" +
	"\rfavorite_type\x18\x02 \x01(\x0e2\x18.profile.v1.FavoriteTypeR\ffavoriteType\x12/\n" +
	"\x05state\x18\x03 \x01(\v2\x19.profile.v1.FavoriteStateR\x05state\x12/\n" +
	"\x05video\x18\x04 \x01(\v2\x19.profile.v1.VideoMetadataR\x05video\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8b\x01\n" +
	"\x0fFavoriteSummary\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12/\n" +
	"\x05state\x18\x02 \x01(\v2\x19.profile.v1.FavoriteStateR\x05state\x12,\n" +
	"\x05stats\x18\x03 \x01(\v2\x16.profile.v1.VideoStatsR\x05stats\"\xf5\x02\n" +
	"\rWatchProgress\x12)\n" +
	"\x10position_seconds\x18\x01 \x01(\x03R\x0fpositionSeconds\x12%\n" +
	"\x0eprogress_ratio\x18\x02 \x01(\x01R\rprogressRatio\x12.\n" +
	"\x13total_watch_seconds\x18\x03 \x01(\x03R\x11totalWatchSeconds\x12D\n" +
	"\x10first_watched_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0efirstWatchedAt\x12B\n" +
	"\x0flast_watched_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rlastWatchedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\"\x96\x01\n" +
	"\x11WatchHistoryEntry\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x125\n" +
	"\bprogress\x18\x02 \x01(\v2\x19.profile.v1.WatchProgressR\bprogress\x12/\n" +
	"\x05video\x18\x03 \x01(\v2\x19.profile.v1.VideoMetadataR\x05video\"\xb9\x03\n" +
	"\rVideoMetadata\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0fduration_micros\x18\x04 \x01(\x03R\x0edurationMicros\x12#\n" +
	"\rthumbnail_url\x18\x05 \x01(\tR\fthumbnailUrl\x12.\n" +
	"\x13hls_master_playlist\x18\x06 \x01(\tR\x11hlsMasterPlaylist\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12+\n" +
	"\x11visibility_status\x18\b \x01(\tR\x10visibilityStatus\x12=\n" +
	"\fpublished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversion\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe6\x01\n" +
	"\n" +
	"VideoStats\x12\x1d\n" +
	"\n" +
	"like_count\x18\x01 \x01(\x03R\tlikeCount\x12%\n" +
	"\x0ebookmark_count\x18\x02 \x01(\x03R\rbookmarkCount\x12'\n" +
	"\x0funique_watchers\x18\x03 \x01(\x03R\x0euniqueWatchers\x12.\n" +
	"\x13total_watch_seconds\x18\x04 \x01(\x03R\x11totalWatchSeconds\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*f\n" +
	"\x0eFavoriteAction\x12\x1f\n" +
	"\x1bFAVORITE_ACTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FAVORITE_ACTION_ADD\x10\x01\x12\x1a\n" +
	"\x16FAVORITE_ACTION_REMOVE\x10\x02*a\n" +
	"\fFavoriteType\x12\x1d\n" +
	"\x19FAVORITE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FAVORITE_TYPE_LIKE\x10\x01\x12\x1a\n" +
	"\x16FAVORITE_TYPE_BOOKMARK\x10\x022\xc6\x06\n" +
	"\x0eProfileService\x12K\n" +
	"\n" +
	"GetProfile\x12\x1d.profile.v1.GetProfileRequest\x1a\x1e.profile.v1.GetProfileResponse\x12T\n" +
	"\rUpdateProfile\x12 .profile.v1.UpdateProfileRequest\x1a!.profile.v1.UpdateProfileResponse\x12`\n" +
	"\x11UpdatePreferences\x12$.profile.v1.UpdatePreferencesRequest\x1a%.profile.v1.UpdatePreferencesResponse\x12W\n" +
	"\x0eMutateFavorite\x12!.profile.v1.MutateFavoriteRequest\x1a\".profile.v1.MutateFavoriteResponse\x12c\n" +
	"\x12BatchQueryFavorite\x12%.profile.v1.BatchQueryFavoriteRequest\x1a&.profile.v1.BatchQueryFavoriteResponse\x12T\n" +
	"\rListFavorites\x12 .profile.v1.ListFavoritesRequest\x1a!.profile.v1.ListFavoritesResponse\x12f\n" +
	"\x13UpsertWatchProgress\x12&.profile.v1.UpsertWatchProgressRequest\x1a'.profile.v1.UpsertWatchProgressResponse\x12]\n" +
	"\x10ListWatchHistory\x12#.profile.v1.ListWatchHistoryRequest\x1a$.profile.v1.ListWatchHistoryResponse\x12T\n" +
	"\rPurgeUserData\x12 .profile.v1.PurgeUserDataRequest\x1a!.profile.v1.PurgeUserDataResponseBHZFgithub.com/bionicotaku/lingo-services-profile/api/profile/v1;profilev1b\x06proto3"

var (
	file_api_profile_v1_profile_proto_rawDescOnce sync.Once
	file_api_profile_v1_profile_proto_rawDescData []byte
)

func file_api_profile_v1_profile_proto_rawDescGZIP() []byte {
	file_api_profile_v1_profile_proto_rawDescOnce.Do(func() {
		file_api_profile_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_profile_v1_profile_proto_rawDesc), len(file_api_profile_v1_profile_proto_rawDesc)))
	})
	return file_api_profile_v1_profile_proto_rawDescData
}

var file_api_profile_v1_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_profile_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_api_profile_v1_profile_proto_goTypes = []any{
	(FavoriteAction)(0),                 // 0: profile.v1.FavoriteAction
	(FavoriteType)(0),                   // 1: profile.v1.FavoriteType
	(*GetProfileRequest)(nil),           // 2: profile.v1.GetProfileRequest
	(*GetProfileResponse)(nil),          // 3: profile.v1.GetProfileResponse
	(*UpdateProfileRequest)(nil),        // 4: profile.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),       // 5: profile.v1.UpdateProfileResponse
	(*UpdatePreferencesRequest)(nil),    // 6: profile.v1.UpdatePreferencesRequest
	(*UpdatePreferencesResponse)(nil),   // 7: profile.v1.UpdatePreferencesResponse
	(*MutateFavoriteRequest)(nil),       // 8: profile.v1.MutateFavoriteRequest
	(*MutateFavoriteResponse)(nil),      // 9: profile.v1.MutateFavoriteResponse
	(*BatchQueryFavoriteRequest)(nil),   // 10: profile.v1.BatchQueryFavoriteRequest
	(*BatchQueryFavoriteResponse)(nil),  // 11: profile.v1.BatchQueryFavoriteResponse
	(*ListFavoritesRequest)(nil),        // 12: profile.v1.ListFavoritesRequest
	(*ListFavoritesResponse)(nil),       // 13: profile.v1.ListFavoritesResponse
	(*UpsertWatchProgressRequest)(nil),  // 14: profile.v1.UpsertWatchProgressRequest
	(*UpsertWatchProgressResponse)(nil), // 15: profile.v1.UpsertWatchProgressResponse
	(*ListWatchHistoryRequest)(nil),     // 16: profile.v1.ListWatchHistoryRequest
	(*ListWatchHistoryResponse)(nil),    // 17: profile.v1.ListWatchHistoryResponse
	(*PurgeUserDataRequest)(nil),        // 18: profile.v1.PurgeUserDataRequest
	(*PurgeUserDataResponse)(nil),       // 19: profile.v1.PurgeUserDataResponse
	(*Profile)(nil),                     // 20: profile.v1.Profile
	(*Preferences)(nil),                 // 21: profile.v1.Preferences
	(*FavoriteState)(nil),               // 22: profile.v1.FavoriteState
	(*FavoriteItem)(nil),                // 23: profile.v1.FavoriteItem
	(*FavoriteSummary)(nil),             // 24: profile.v1.FavoriteSummary
	(*WatchProgress)(nil),               // 25: profile.v1.WatchProgress
	(*WatchHistoryEntry)(nil),           // 26: profile.v1.WatchHistoryEntry
	(*VideoMetadata)(nil),               // 27: profile.v1.VideoMetadata
	(*VideoStats)(nil),                  // 28: profile.v1.VideoStats
	(*fieldmaskpb.FieldMask)(nil),       // 29: google.protobuf.FieldMask
	(*wrapperspb.Int64Value)(nil),       // 30: google.protobuf.Int64Value
	(*timestamppb.Timestamp)(nil),       // 31: google.protobuf.Timestamp
	(*wrapperspb.Int32Value)(nil),       // 32: google.protobuf.Int32Value
	(*structpb.Struct)(nil),             // 33: google.protobuf.Struct
}
var file_api_profile_v1_profile_proto_depIdxs = []int32{
	20, // 0: profile.v1.GetProfileResponse.profile:type_name -> profile.v1.Profile
	20, // 1: profile.v1.UpdateProfileRequest.profile:type_name -> profile.v1.Profile
	29, // 2: profile.v1.UpdateProfileRequest.update_mask:type_name -> google.protobuf.FieldMask
	30, // 3: profile.v1.UpdateProfileRequest.expected_profile_version:type_name -> google.protobuf.Int64Value
	20, // 4: profile.v1.UpdateProfileResponse.profile:type_name -> profile.v1.Profile
	21, // 5: profile.v1.UpdatePreferencesRequest.preferences:type_name -> profile.v1.Preferences
	29, // 6: profile.v1.UpdatePreferencesRequest.update_mask:type_name -> google.protobuf.FieldMask
	30, // 7: profile.v1.UpdatePreferencesRequest.expected_profile_version:type_name -> google.protobuf.Int64Value
	20, // 8: profile.v1.UpdatePreferencesResponse.profile:type_name -> profile.v1.Profile
	1,  // 9: profile.v1.MutateFavoriteRequest.favorite_type:type_name -> profile.v1.FavoriteType
	0,  // 10: profile.v1.MutateFavoriteRequest.action:type_name -> profile.v1.FavoriteAction
	31, // 11: profile.v1.MutateFavoriteRequest.occurred_at:type_name -> google.protobuf.Timestamp
	22, // 12: profile.v1.MutateFavoriteResponse.state:type_name -> profile.v1.FavoriteState
	28, // 13: profile.v1.MutateFavoriteResponse.stats:type_name -> profile.v1.VideoStats
	24, // 14: profile.v1.BatchQueryFavoriteResponse.summaries:type_name -> profile.v1.FavoriteSummary
	23, // 15: profile.v1.ListFavoritesResponse.favorites:type_name -> profile.v1.FavoriteItem
	25, // 16: profile.v1.UpsertWatchProgressRequest.progress:type_name -> profile.v1.WatchProgress
	25, // 17: profile.v1.UpsertWatchProgressResponse.progress:type_name -> profile.v1.WatchProgress
	28, // 18: profile.v1.UpsertWatchProgressResponse.stats:type_name -> profile.v1.VideoStats
	26, // 19: profile.v1.ListWatchHistoryResponse.items:type_name -> profile.v1.WatchHistoryEntry
	21, // 20: profile.v1.Profile.preferences:type_name -> profile.v1.Preferences
	31, // 21: profile.v1.Profile.created_at:type_name -> google.protobuf.Timestamp
	31, // 22: profile.v1.Profile.updated_at:type_name -> google.protobuf.Timestamp
	32, // 23: profile.v1.Preferences.daily_quota_minutes:type_name -> google.protobuf.Int32Value
	33, // 24: profile.v1.Preferences.extra:type_name -> google.protobuf.Struct
	31, // 25: profile.v1.FavoriteState.liked_at:type_name -> google.protobuf.Timestamp
	31, // 26: profile.v1.FavoriteState.bookmarked_at:type_name -> google.protobuf.Timestamp
	1,  // 27: profile.v1.FavoriteItem.favorite_type:type_name -> profile.v1.FavoriteType
	22, // 28: profile.v1.FavoriteItem.state:type_name -> profile.v1.FavoriteState
	27, // 29: profile.v1.FavoriteItem.video:type_name -> profile.v1.VideoMetadata
	31, // 30: profile.v1.FavoriteItem.created_at:type_name -> google.protobuf.Timestamp
	31, // 31: profile.v1.FavoriteItem.updated_at:type_name -> google.protobuf.Timestamp
	22, // 32: profile.v1.FavoriteSummary.state:type_name -> profile.v1.FavoriteState
	28, // 33: profile.v1.FavoriteSummary.stats:type_name -> profile.v1.VideoStats
	31, // 34: profile.v1.WatchProgress.first_watched_at:type_name -> google.protobuf.Timestamp
	31, // 35: profile.v1.WatchProgress.last_watched_at:type_name -> google.protobuf.Timestamp
	31, // 36: profile.v1.WatchProgress.expires_at:type_name -> google.protobuf.Timestamp
	25, // 37: profile.v1.WatchHistoryEntry.progress:type_name -> profile.v1.WatchProgress
	27, // 38: profile.v1.WatchHistoryEntry.video:type_name -> profile.v1.VideoMetadata
	31, // 39: profile.v1.VideoMetadata.published_at:type_name -> google.protobuf.Timestamp
	31, // 40: profile.v1.VideoMetadata.updated_at:type_name -> google.protobuf.Timestamp
	31, // 41: profile.v1.VideoStats.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 42: profile.v1.ProfileService.GetProfile:input_type -> profile.v1.GetProfileRequest
	4,  // 43: profile.v1.ProfileService.UpdateProfile:input_type -> profile.v1.UpdateProfileRequest
	6,  // 44: profile.v1.ProfileService.UpdatePreferences:input_type -> profile.v1.UpdatePreferencesRequest
	8,  // 45: profile.v1.ProfileService.MutateFavorite:input_type -> profile.v1.MutateFavoriteRequest
	10, // 46: profile.v1.ProfileService.BatchQueryFavorite:input_type -> profile.v1.BatchQueryFavoriteRequest
	12, // 47: profile.v1.ProfileService.ListFavorites:input_type -> profile.v1.ListFavoritesRequest
	14, // 48: profile.v1.ProfileService.UpsertWatchProgress:input_type -> profile.v1.UpsertWatchProgressRequest
	16, // 49: profile.v1.ProfileService.ListWatchHistory:input_type -> profile.v1.ListWatchHistoryRequest
	18, // 50: profile.v1.ProfileService.PurgeUserData:input_type -> profile.v1.PurgeUserDataRequest
	3,  // 51: profile.v1.ProfileService.GetProfile:output_type -> profile.v1.GetProfileResponse
	5,  // 52: profile.v1.ProfileService.UpdateProfile:output_type -> profile.v1.UpdateProfileResponse
	7,  // 53: profile.v1.ProfileService.UpdatePreferences:output_type -> profile.v1.UpdatePreferencesResponse
	9,  // 54: profile.v1.ProfileService.MutateFavorite:output_type -> profile.v1.MutateFavoriteResponse
	11, // 55: profile.v1.ProfileService.BatchQueryFavorite:output_type -> profile.v1.BatchQueryFavoriteResponse
	13, // 56: profile.v1.ProfileService.ListFavorites:output_type -> profile.v1.ListFavoritesResponse
	15, // 57: profile.v1.ProfileService.UpsertWatchProgress:output_type -> profile.v1.UpsertWatchProgressResponse
	17, // 58: profile.v1.ProfileService.ListWatchHistory:output_type -> profile.v1.ListWatchHistoryResponse
	19, // 59: profile.v1.ProfileService.PurgeUserData:output_type -> profile.v1.PurgeUserDataResponse
	51, // [51:60] is the sub-list for method output_type
	42, // [42:51] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_api_profile_v1_profile_proto_init() }
func file_api_profile_v1_profile_proto_init() {
	if File_api_profile_v1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_profile_v1_profile_proto_rawDesc), len(file_api_profile_v1_profile_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_profile_v1_profile_proto_goTypes,
		DependencyIndexes: file_api_profile_v1_profile_proto_depIdxs,
		EnumInfos:         file_api_profile_v1_profile_proto_enumTypes,
		MessageInfos:      file_api_profile_v1_profile_proto_msgTypes,
	}.Build()
	File_api_profile_v1_profile_proto = out.File
	file_api_profile_v1_profile_proto_goTypes = nil
	file_api_profile_v1_profile_proto_depIdxs = nil
}
