// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/video/v1/error_reason.proto

package videov1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason 定义视频相关的错误码。
type ErrorReason int32

const (
	// 默认未指定错误
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	// 视频未找到
	ErrorReason_ERROR_REASON_VIDEO_NOT_FOUND ErrorReason = 1
	// 视频 ID 无效
	ErrorReason_ERROR_REASON_VIDEO_ID_INVALID ErrorReason = 2
	// 查询视频失败
	ErrorReason_ERROR_REASON_QUERY_VIDEO_FAILED ErrorReason = 3
	// 查询超时
	ErrorReason_ERROR_REASON_QUERY_TIMEOUT ErrorReason = 4
	// 更新请求无效（缺少字段或取值非法）
	ErrorReason_ERROR_REASON_VIDEO_UPDATE_INVALID ErrorReason = 5
	// 删除请求无效
	ErrorReason_ERROR_REASON_VIDEO_DELETE_INVALID ErrorReason = 6
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "ERROR_REASON_UNSPECIFIED",
		1: "ERROR_REASON_VIDEO_NOT_FOUND",
		2: "ERROR_REASON_VIDEO_ID_INVALID",
		3: "ERROR_REASON_QUERY_VIDEO_FAILED",
		4: "ERROR_REASON_QUERY_TIMEOUT",
		5: "ERROR_REASON_VIDEO_UPDATE_INVALID",
		6: "ERROR_REASON_VIDEO_DELETE_INVALID",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED":          0,
		"ERROR_REASON_VIDEO_NOT_FOUND":      1,
		"ERROR_REASON_VIDEO_ID_INVALID":     2,
		"ERROR_REASON_QUERY_VIDEO_FAILED":   3,
		"ERROR_REASON_QUERY_TIMEOUT":        4,
		"ERROR_REASON_VIDEO_UPDATE_INVALID": 5,
		"ERROR_REASON_VIDEO_DELETE_INVALID": 6,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_video_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_api_video_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_video_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_api_video_v1_error_reason_proto protoreflect.FileDescriptor

const file_api_video_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/video/v1/error_reason.proto\x12\bvideo.v1*\x83\x02\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cERROR_REASON_VIDEO_NOT_FOUND\x10\x01\x12!\n" +
	"\x1dERROR_REASON_VIDEO_ID_INVALID\x10\x02\x12#\n" +
	"\x1fERROR_REASON_QUERY_VIDEO_FAILED\x10\x03\x12\x1e\n" +
	"\x1aERROR_REASON_QUERY_TIMEOUT\x10\x04\x12%\n" +
	"!ERROR_REASON_VIDEO_UPDATE_INVALID\x10\x05\x12%\n" +
	"!ERROR_REASON_VIDEO_DELETE_INVALID\x10\x06BDZBgithub.com/bionicotaku/lingo-services-catalog/api/video/v1;videov1b\x06proto3"

var (
	file_api_video_v1_error_reason_proto_rawDescOnce sync.Once
	file_api_video_v1_error_reason_proto_rawDescData []byte
)

func file_api_video_v1_error_reason_proto_rawDescGZIP() []byte {
	file_api_video_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_api_video_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_video_v1_error_reason_proto_rawDesc), len(file_api_video_v1_error_reason_proto_rawDesc)))
	})
	return file_api_video_v1_error_reason_proto_rawDescData
}

var file_api_video_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_video_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: video.v1.ErrorReason
}
var file_api_video_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_video_v1_error_reason_proto_init() }
func file_api_video_v1_error_reason_proto_init() {
	if File_api_video_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_video_v1_error_reason_proto_rawDesc), len(file_api_video_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_video_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_api_video_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_api_video_v1_error_reason_proto_enumTypes,
	}.Build()
	File_api_video_v1_error_reason_proto = out.File
	file_api_video_v1_error_reason_proto_goTypes = nil
	file_api_video_v1_error_reason_proto_depIdxs = nil
}
