// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/video/v1/events.proto

package videov1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType 定义事件类型枚举
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED              EventType = 0
	EventType_EVENT_TYPE_VIDEO_CREATED            EventType = 1
	EventType_EVENT_TYPE_VIDEO_UPDATED            EventType = 2
	EventType_EVENT_TYPE_VIDEO_DELETED            EventType = 3
	EventType_EVENT_TYPE_VIDEO_MEDIA_READY        EventType = 4
	EventType_EVENT_TYPE_VIDEO_AI_ENRICHED        EventType = 5
	EventType_EVENT_TYPE_VIDEO_PROCESSING_FAILED  EventType = 6
	EventType_EVENT_TYPE_VIDEO_VISIBILITY_CHANGED EventType = 7
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_VIDEO_CREATED",
		2: "EVENT_TYPE_VIDEO_UPDATED",
		3: "EVENT_TYPE_VIDEO_DELETED",
		4: "EVENT_TYPE_VIDEO_MEDIA_READY",
		5: "EVENT_TYPE_VIDEO_AI_ENRICHED",
		6: "EVENT_TYPE_VIDEO_PROCESSING_FAILED",
		7: "EVENT_TYPE_VIDEO_VISIBILITY_CHANGED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":              0,
		"EVENT_TYPE_VIDEO_CREATED":            1,
		"EVENT_TYPE_VIDEO_UPDATED":            2,
		"EVENT_TYPE_VIDEO_DELETED":            3,
		"EVENT_TYPE_VIDEO_MEDIA_READY":        4,
		"EVENT_TYPE_VIDEO_AI_ENRICHED":        5,
		"EVENT_TYPE_VIDEO_PROCESSING_FAILED":  6,
		"EVENT_TYPE_VIDEO_VISIBILITY_CHANGED": 7,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_video_v1_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_api_video_v1_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_video_v1_events_proto_rawDescGZIP(), []int{0}
}

// Event 是通用事件信封（Envelope）
// 用于统一封装不同类型的事件，便于序列化、传输和处理
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                                // 事件唯一标识 (UUID)
	EventType     EventType              `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=video.v1.EventType" json:"event_type,omitempty"` // 事件类型
	AggregateId   string                 `protobuf:"bytes,3,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`                    // 聚合根 ID (通常是 video_id)
	AggregateType string                 `protobuf:"bytes,4,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`              // 聚合类型（如 "video"）
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`                                              // 聚合版本号
	OccurredAt    string                 `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`                       // 事件发生时间（UTC RFC3339）
	// 使用 oneof 实现多态，根据 event_type 包含对应的 payload
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Created
	//	*Event_Updated
	//	*Event_Deleted
	//	*Event_MediaReady
	//	*Event_AiEnriched
	//	*Event_ProcessingFailed
	//	*Event_VisibilityChanged
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_video_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_video_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *Event) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *Event) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetCreated() *Event_VideoCreated {
	if x != nil {
		if x, ok := x.Payload.(*Event_Created); ok {
			return x.Created
		}
	}
	return nil
}

func (x *Event) GetUpdated() *Event_VideoUpdated {
	if x != nil {
		if x, ok := x.Payload.(*Event_Updated); ok {
			return x.Updated
		}
	}
	return nil
}

func (x *Event) GetDeleted() *Event_VideoDeleted {
	if x != nil {
		if x, ok := x.Payload.(*Event_Deleted); ok {
			return x.Deleted
		}
	}
	return nil
}

func (x *Event) GetMediaReady() *Event_VideoMediaReady {
	if x != nil {
		if x, ok := x.Payload.(*Event_MediaReady); ok {
			return x.MediaReady
		}
	}
	return nil
}

func (x *Event) GetAiEnriched() *Event_VideoAIEnriched {
	if x != nil {
		if x, ok := x.Payload.(*Event_AiEnriched); ok {
			return x.AiEnriched
		}
	}
	return nil
}

func (x *Event) GetProcessingFailed() *Event_VideoProcessingFailed {
	if x != nil {
		if x, ok := x.Payload.(*Event_ProcessingFailed); ok {
			return x.ProcessingFailed
		}
	}
	return nil
}

func (x *Event) GetVisibilityChanged() *Event_VideoVisibilityChanged {
	if x != nil {
		if x, ok := x.Payload.(*Event_VisibilityChanged); ok {
			return x.VisibilityChanged
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Created struct {
	Created *Event_VideoCreated `protobuf:"bytes,10,opt,name=created,proto3,oneof"`
}

type Event_Updated struct {
	Updated *Event_VideoUpdated `protobuf:"bytes,11,opt,name=updated,proto3,oneof"`
}

type Event_Deleted struct {
	Deleted *Event_VideoDeleted `protobuf:"bytes,12,opt,name=deleted,proto3,oneof"`
}

type Event_MediaReady struct {
	MediaReady *Event_VideoMediaReady `protobuf:"bytes,13,opt,name=media_ready,json=mediaReady,proto3,oneof"`
}

type Event_AiEnriched struct {
	AiEnriched *Event_VideoAIEnriched `protobuf:"bytes,14,opt,name=ai_enriched,json=aiEnriched,proto3,oneof"`
}

type Event_ProcessingFailed struct {
	ProcessingFailed *Event_VideoProcessingFailed `protobuf:"bytes,15,opt,name=processing_failed,json=processingFailed,proto3,oneof"`
}

type Event_VisibilityChanged struct {
	VisibilityChanged *Event_VideoVisibilityChanged `protobuf:"bytes,16,opt,name=visibility_changed,json=visibilityChanged,proto3,oneof"`
}

func (*Event_Created) isEvent_Payload() {}

func (*Event_Updated) isEvent_Payload() {}

func (*Event_Deleted) isEvent_Payload() {}

func (*Event_MediaReady) isEvent_Payload() {}

func (*Event_AiEnriched) isEvent_Payload() {}

func (*Event_ProcessingFailed) isEvent_Payload() {}

func (*Event_VisibilityChanged) isEvent_Payload() {}

// VideoCreated 表示视频创建事件
// 当一个新视频元数据被创建时发布此事件
type Event_VideoCreated struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`                             // 视频唯一标识 (UUID)
	UploaderId     string                 `protobuf:"bytes,2,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`                    // 上传者标识 (UUID)
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                                                // 视频标题
	Description    *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`                              // 视频描述（可选）
	DurationMicros *int64                 `protobuf:"varint,5,opt,name=duration_micros,json=durationMicros,proto3,oneof" json:"duration_micros,omitempty"` // 视频时长（微秒，可选）
	PublishedAt    *string                `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`           // 视频发布时间（UTC RFC3339，可选）
	Version        int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`                                           // 聚合版本号
	OccurredAt     string                 `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`                    // 事件发生时间（UTC RFC3339）
	Status         string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`                                              // 视频状态
	MediaStatus    string                 `protobuf:"bytes,10,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`                // 媒体处理状态
	AnalysisStatus string                 `protobuf:"bytes,11,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"`       // 分析状态
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event_VideoCreated) Reset() {
	*x = Event_VideoCreated{}
	mi := &file_api_video_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_VideoCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_VideoCreated) ProtoMessage() {}

func (x *Event_VideoCreated) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_VideoCreated.ProtoReflect.Descriptor instead.
func (*Event_VideoCreated) Descriptor() ([]byte, []int) {
	return file_api_video_v1_events_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Event_VideoCreated) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Event_VideoCreated) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *Event_VideoCreated) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event_VideoCreated) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Event_VideoCreated) GetDurationMicros() int64 {
	if x != nil && x.DurationMicros != nil {
		return *x.DurationMicros
	}
	return 0
}

func (x *Event_VideoCreated) GetPublishedAt() string {
	if x != nil && x.PublishedAt != nil {
		return *x.PublishedAt
	}
	return ""
}

func (x *Event_VideoCreated) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event_VideoCreated) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *Event_VideoCreated) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Event_VideoCreated) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

func (x *Event_VideoCreated) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

// VideoUpdated 表示视频更新事件
// 当视频元数据被更新时发布此事件
// 只包含被更新的字段（部分更新语义）
type Event_VideoUpdated struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	VideoId    string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`          // 视频唯一标识 (UUID)
	Version    int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                        // 新版本号
	OccurredAt string                 `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // 事件发生时间（UTC RFC3339）
	// 以下字段为可选，仅包含实际被更新的字段
	Title             *string  `protobuf:"bytes,10,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description       *string  `protobuf:"bytes,11,opt,name=description,proto3,oneof" json:"description,omitempty"`
	DurationMicros    *int64   `protobuf:"varint,12,opt,name=duration_micros,json=durationMicros,proto3,oneof" json:"duration_micros,omitempty"`
	Status            *string  `protobuf:"bytes,13,opt,name=status,proto3,oneof" json:"status,omitempty"`
	MediaStatus       *string  `protobuf:"bytes,14,opt,name=media_status,json=mediaStatus,proto3,oneof" json:"media_status,omitempty"`
	AnalysisStatus    *string  `protobuf:"bytes,15,opt,name=analysis_status,json=analysisStatus,proto3,oneof" json:"analysis_status,omitempty"`
	ThumbnailUrl      *string  `protobuf:"bytes,16,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	HlsMasterPlaylist *string  `protobuf:"bytes,17,opt,name=hls_master_playlist,json=hlsMasterPlaylist,proto3,oneof" json:"hls_master_playlist,omitempty"`
	Difficulty        *string  `protobuf:"bytes,18,opt,name=difficulty,proto3,oneof" json:"difficulty,omitempty"`
	Summary           *string  `protobuf:"bytes,19,opt,name=summary,proto3,oneof" json:"summary,omitempty"`
	Tags              []string `protobuf:"bytes,20,rep,name=tags,proto3" json:"tags,omitempty"`
	RawSubtitleUrl    *string  `protobuf:"bytes,21,opt,name=raw_subtitle_url,json=rawSubtitleUrl,proto3,oneof" json:"raw_subtitle_url,omitempty"`
	PublishedAt       *string  `protobuf:"bytes,22,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	VisibilityStatus  *string  `protobuf:"bytes,23,opt,name=visibility_status,json=visibilityStatus,proto3,oneof" json:"visibility_status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Event_VideoUpdated) Reset() {
	*x = Event_VideoUpdated{}
	mi := &file_api_video_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_VideoUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_VideoUpdated) ProtoMessage() {}

func (x *Event_VideoUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_VideoUpdated.ProtoReflect.Descriptor instead.
func (*Event_VideoUpdated) Descriptor() ([]byte, []int) {
	return file_api_video_v1_events_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Event_VideoUpdated) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Event_VideoUpdated) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event_VideoUpdated) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *Event_VideoUpdated) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Event_VideoUpdated) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Event_VideoUpdated) GetDurationMicros() int64 {
	if x != nil && x.DurationMicros != nil {
		return *x.DurationMicros
	}
	return 0
}

func (x *Event_VideoUpdated) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *Event_VideoUpdated) GetMediaStatus() string {
	if x != nil && x.MediaStatus != nil {
		return *x.MediaStatus
	}
	return ""
}

func (x *Event_VideoUpdated) GetAnalysisStatus() string {
	if x != nil && x.AnalysisStatus != nil {
		return *x.AnalysisStatus
	}
	return ""
}

func (x *Event_VideoUpdated) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *Event_VideoUpdated) GetHlsMasterPlaylist() string {
	if x != nil && x.HlsMasterPlaylist != nil {
		return *x.HlsMasterPlaylist
	}
	return ""
}

func (x *Event_VideoUpdated) GetDifficulty() string {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return ""
}

func (x *Event_VideoUpdated) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

func (x *Event_VideoUpdated) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event_VideoUpdated) GetRawSubtitleUrl() string {
	if x != nil && x.RawSubtitleUrl != nil {
		return *x.RawSubtitleUrl
	}
	return ""
}

func (x *Event_VideoUpdated) GetPublishedAt() string {
	if x != nil && x.PublishedAt != nil {
		return *x.PublishedAt
	}
	return ""
}

func (x *Event_VideoUpdated) GetVisibilityStatus() string {
	if x != nil && x.VisibilityStatus != nil {
		return *x.VisibilityStatus
	}
	return ""
}

// VideoDeleted 表示视频删除事件
// 当视频被删除时发布此事件
type Event_VideoDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`             // 视频唯一标识 (UUID)
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                           // 版本号
	DeletedAt     *string                `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"` // 删除时间（UTC RFC3339，可选）
	OccurredAt    string                 `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`    // 事件发生时间（UTC RFC3339）
	Reason        *string                `protobuf:"bytes,5,opt,name=reason,proto3,oneof" json:"reason,omitempty"`                        // 删除原因（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_VideoDeleted) Reset() {
	*x = Event_VideoDeleted{}
	mi := &file_api_video_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_VideoDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_VideoDeleted) ProtoMessage() {}

func (x *Event_VideoDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_VideoDeleted.ProtoReflect.Descriptor instead.
func (*Event_VideoDeleted) Descriptor() ([]byte, []int) {
	return file_api_video_v1_events_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Event_VideoDeleted) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Event_VideoDeleted) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event_VideoDeleted) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

func (x *Event_VideoDeleted) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *Event_VideoDeleted) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// VideoMediaReady 表示媒体阶段完成事件
type Event_VideoMediaReady struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VideoId           string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Version           int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	OccurredAt        string                 `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	MediaStatus       string                 `protobuf:"bytes,5,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`
	DurationMicros    *int64                 `protobuf:"varint,6,opt,name=duration_micros,json=durationMicros,proto3,oneof" json:"duration_micros,omitempty"`
	EncodedResolution *string                `protobuf:"bytes,7,opt,name=encoded_resolution,json=encodedResolution,proto3,oneof" json:"encoded_resolution,omitempty"`
	EncodedBitrate    *int32                 `protobuf:"varint,8,opt,name=encoded_bitrate,json=encodedBitrate,proto3,oneof" json:"encoded_bitrate,omitempty"`
	ThumbnailUrl      *string                `protobuf:"bytes,9,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	HlsMasterPlaylist *string                `protobuf:"bytes,10,opt,name=hls_master_playlist,json=hlsMasterPlaylist,proto3,oneof" json:"hls_master_playlist,omitempty"`
	JobId             *string                `protobuf:"bytes,11,opt,name=job_id,json=jobId,proto3,oneof" json:"job_id,omitempty"`
	EmittedAt         *string                `protobuf:"bytes,12,opt,name=emitted_at,json=emittedAt,proto3,oneof" json:"emitted_at,omitempty"`
	AnalysisStatus    string                 `protobuf:"bytes,13,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Event_VideoMediaReady) Reset() {
	*x = Event_VideoMediaReady{}
	mi := &file_api_video_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_VideoMediaReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_VideoMediaReady) ProtoMessage() {}

func (x *Event_VideoMediaReady) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_VideoMediaReady.ProtoReflect.Descriptor instead.
func (*Event_VideoMediaReady) Descriptor() ([]byte, []int) {
	return file_api_video_v1_events_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Event_VideoMediaReady) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Event_VideoMediaReady) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event_VideoMediaReady) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *Event_VideoMediaReady) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Event_VideoMediaReady) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

func (x *Event_VideoMediaReady) GetDurationMicros() int64 {
	if x != nil && x.DurationMicros != nil {
		return *x.DurationMicros
	}
	return 0
}

func (x *Event_VideoMediaReady) GetEncodedResolution() string {
	if x != nil && x.EncodedResolution != nil {
		return *x.EncodedResolution
	}
	return ""
}

func (x *Event_VideoMediaReady) GetEncodedBitrate() int32 {
	if x != nil && x.EncodedBitrate != nil {
		return *x.EncodedBitrate
	}
	return 0
}

func (x *Event_VideoMediaReady) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *Event_VideoMediaReady) GetHlsMasterPlaylist() string {
	if x != nil && x.HlsMasterPlaylist != nil {
		return *x.HlsMasterPlaylist
	}
	return ""
}

func (x *Event_VideoMediaReady) GetJobId() string {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return ""
}

func (x *Event_VideoMediaReady) GetEmittedAt() string {
	if x != nil && x.EmittedAt != nil {
		return *x.EmittedAt
	}
	return ""
}

func (x *Event_VideoMediaReady) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

// VideoAIEnriched 表示 AI 阶段完成事件
type Event_VideoAIEnriched struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Version        int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	OccurredAt     string                 `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AnalysisStatus string                 `protobuf:"bytes,5,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"`
	Difficulty     *string                `protobuf:"bytes,6,opt,name=difficulty,proto3,oneof" json:"difficulty,omitempty"`
	Summary        *string                `protobuf:"bytes,7,opt,name=summary,proto3,oneof" json:"summary,omitempty"`
	Tags           []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	RawSubtitleUrl *string                `protobuf:"bytes,9,opt,name=raw_subtitle_url,json=rawSubtitleUrl,proto3,oneof" json:"raw_subtitle_url,omitempty"`
	JobId          *string                `protobuf:"bytes,10,opt,name=job_id,json=jobId,proto3,oneof" json:"job_id,omitempty"`
	EmittedAt      *string                `protobuf:"bytes,11,opt,name=emitted_at,json=emittedAt,proto3,oneof" json:"emitted_at,omitempty"`
	ErrorMessage   *string                `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	MediaStatus    string                 `protobuf:"bytes,13,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event_VideoAIEnriched) Reset() {
	*x = Event_VideoAIEnriched{}
	mi := &file_api_video_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_VideoAIEnriched) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_VideoAIEnriched) ProtoMessage() {}

func (x *Event_VideoAIEnriched) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_VideoAIEnriched.ProtoReflect.Descriptor instead.
func (*Event_VideoAIEnriched) Descriptor() ([]byte, []int) {
	return file_api_video_v1_events_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Event_VideoAIEnriched) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Event_VideoAIEnriched) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event_VideoAIEnriched) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *Event_VideoAIEnriched) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Event_VideoAIEnriched) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

func (x *Event_VideoAIEnriched) GetDifficulty() string {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return ""
}

func (x *Event_VideoAIEnriched) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

func (x *Event_VideoAIEnriched) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event_VideoAIEnriched) GetRawSubtitleUrl() string {
	if x != nil && x.RawSubtitleUrl != nil {
		return *x.RawSubtitleUrl
	}
	return ""
}

func (x *Event_VideoAIEnriched) GetJobId() string {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return ""
}

func (x *Event_VideoAIEnriched) GetEmittedAt() string {
	if x != nil && x.EmittedAt != nil {
		return *x.EmittedAt
	}
	return ""
}

func (x *Event_VideoAIEnriched) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *Event_VideoAIEnriched) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

// VideoProcessingFailed 表示处理阶段失败事件
type Event_VideoProcessingFailed struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Version        int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	OccurredAt     string                 `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	FailedStage    string                 `protobuf:"bytes,4,opt,name=failed_stage,json=failedStage,proto3" json:"failed_stage,omitempty"`
	ErrorMessage   *string                `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	JobId          *string                `protobuf:"bytes,6,opt,name=job_id,json=jobId,proto3,oneof" json:"job_id,omitempty"`
	EmittedAt      *string                `protobuf:"bytes,7,opt,name=emitted_at,json=emittedAt,proto3,oneof" json:"emitted_at,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	MediaStatus    string                 `protobuf:"bytes,9,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`
	AnalysisStatus string                 `protobuf:"bytes,10,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event_VideoProcessingFailed) Reset() {
	*x = Event_VideoProcessingFailed{}
	mi := &file_api_video_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_VideoProcessingFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_VideoProcessingFailed) ProtoMessage() {}

func (x *Event_VideoProcessingFailed) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_VideoProcessingFailed.ProtoReflect.Descriptor instead.
func (*Event_VideoProcessingFailed) Descriptor() ([]byte, []int) {
	return file_api_video_v1_events_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Event_VideoProcessingFailed) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Event_VideoProcessingFailed) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event_VideoProcessingFailed) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *Event_VideoProcessingFailed) GetFailedStage() string {
	if x != nil {
		return x.FailedStage
	}
	return ""
}

func (x *Event_VideoProcessingFailed) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *Event_VideoProcessingFailed) GetJobId() string {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return ""
}

func (x *Event_VideoProcessingFailed) GetEmittedAt() string {
	if x != nil && x.EmittedAt != nil {
		return *x.EmittedAt
	}
	return ""
}

func (x *Event_VideoProcessingFailed) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Event_VideoProcessingFailed) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

func (x *Event_VideoProcessingFailed) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

// VideoVisibilityChanged 表示可见性变化事件
type Event_VideoVisibilityChanged struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VideoId          string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Version          int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	OccurredAt       string                 `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	PreviousStatus   *string                `protobuf:"bytes,5,opt,name=previous_status,json=previousStatus,proto3,oneof" json:"previous_status,omitempty"`
	PublishedAt      *string                `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	Reason           *string                `protobuf:"bytes,7,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	VisibilityStatus *string                `protobuf:"bytes,10,opt,name=visibility_status,json=visibilityStatus,proto3,oneof" json:"visibility_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Event_VideoVisibilityChanged) Reset() {
	*x = Event_VideoVisibilityChanged{}
	mi := &file_api_video_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_VideoVisibilityChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_VideoVisibilityChanged) ProtoMessage() {}

func (x *Event_VideoVisibilityChanged) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_VideoVisibilityChanged.ProtoReflect.Descriptor instead.
func (*Event_VideoVisibilityChanged) Descriptor() ([]byte, []int) {
	return file_api_video_v1_events_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Event_VideoVisibilityChanged) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Event_VideoVisibilityChanged) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event_VideoVisibilityChanged) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *Event_VideoVisibilityChanged) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Event_VideoVisibilityChanged) GetPreviousStatus() string {
	if x != nil && x.PreviousStatus != nil {
		return *x.PreviousStatus
	}
	return ""
}

func (x *Event_VideoVisibilityChanged) GetPublishedAt() string {
	if x != nil && x.PublishedAt != nil {
		return *x.PublishedAt
	}
	return ""
}

func (x *Event_VideoVisibilityChanged) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *Event_VideoVisibilityChanged) GetVisibilityStatus() string {
	if x != nil && x.VisibilityStatus != nil {
		return *x.VisibilityStatus
	}
	return ""
}

var File_api_video_v1_events_proto protoreflect.FileDescriptor

const file_api_video_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x19api/video/v1/events.proto\x12\bvideo.v1\"\xd2 \n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x122\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x13.video.v1.EventTypeR\teventType\x12!\n" +
	"\faggregate_id\x18\x03 \x01(\tR\vaggregateId\x12%\n" +
	"\x0eaggregate_type\x18\x04 \x01(\tR\raggregateType\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12\x1f\n" +
	"\voccurred_at\x18\x06 \x01(\tR\n" +
	"occurredAt\x128\n" +
	"\acreated\x18\n" +
	" \x01(\v2\x1c.video.v1.Event.VideoCreatedH\x00R\acreated\x128\n" +
	"\aupdated\x18\v \x01(\v2\x1c.video.v1.Event.VideoUpdatedH\x00R\aupdated\x128\n" +
	"\adeleted\x18\f \x01(\v2\x1c.video.v1.Event.VideoDeletedH\x00R\adeleted\x12B\n" +
	"\vmedia_ready\x18\r \x01(\v2\x1f.video.v1.Event.VideoMediaReadyH\x00R\n" +
	"mediaReady\x12B\n" +
	"\vai_enriched\x18\x0e \x01(\v2\x1f.video.v1.Event.VideoAIEnrichedH\x00R\n" +
	"aiEnriched\x12T\n" +
	"\x11processing_failed\x18\x0f \x01(\v2%.video.v1.Event.VideoProcessingFailedH\x00R\x10processingFailed\x12W\n" +
	"\x12visibility_changed\x18\x10 \x01(\v2&.video.v1.Event.VideoVisibilityChangedH\x00R\x11visibilityChanged\x1a\xb1\x03\n" +
	"\fVideoCreated\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1f\n" +
	"\vuploader_id\x18\x02 \x01(\tR\n" +
	"uploaderId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12,\n" +
	"\x0fduration_micros\x18\x05 \x01(\x03H\x01R\x0edurationMicros\x88\x01\x01\x12&\n" +
	"\fpublished_at\x18\x06 \x01(\tH\x02R\vpublishedAt\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12\x1f\n" +
	"\voccurred_at\x18\b \x01(\tR\n" +
	"occurredAt\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12!\n" +
	"\fmedia_status\x18\n" +
	" \x01(\tR\vmediaStatus\x12'\n" +
	"\x0fanalysis_status\x18\v \x01(\tR\x0eanalysisStatusB\x0e\n" +
	"\f_descriptionB\x12\n" +
	"\x10_duration_microsB\x0f\n" +
	"\r_published_at\x1a\xe6\x06\n" +
	"\fVideoUpdated\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1f\n" +
	"\voccurred_at\x18\x03 \x01(\tR\n" +
	"occurredAt\x12\x19\n" +
	"\x05title\x18\n" +
	" \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\v \x01(\tH\x01R\vdescription\x88\x01\x01\x12,\n" +
	"\x0fduration_micros\x18\f \x01(\x03H\x02R\x0edurationMicros\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\r \x01(\tH\x03R\x06status\x88\x01\x01\x12&\n" +
	"\fmedia_status\x18\x0e \x01(\tH\x04R\vmediaStatus\x88\x01\x01\x12,\n" +
	"\x0fanalysis_status\x18\x0f \x01(\tH\x05R\x0eanalysisStatus\x88\x01\x01\x12(\n" +
	"\rthumbnail_url\x18\x10 \x01(\tH\x06R\fthumbnailUrl\x88\x01\x01\x123\n" +
	"\x13hls_master_playlist\x18\x11 \x01(\tH\aR\x11hlsMasterPlaylist\x88\x01\x01\x12#\n" +
	"\n" +
	"difficulty\x18\x12 \x01(\tH\bR\n" +
	"difficulty\x88\x01\x01\x12\x1d\n" +
	"\asummary\x18\x13 \x01(\tH\tR\asummary\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x14 \x03(\tR\x04tags\x12-\n" +
	"\x10raw_subtitle_url\x18\x15 \x01(\tH\n" +
	"R\x0erawSubtitleUrl\x88\x01\x01\x12&\n" +
	"\fpublished_at\x18\x16 \x01(\tH\vR\vpublishedAt\x88\x01\x01\x120\n" +
	"\x11visibility_status\x18\x17 \x01(\tH\fR\x10visibilityStatus\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x12\n" +
	"\x10_duration_microsB\t\n" +
	"\a_statusB\x0f\n" +
	"\r_media_statusB\x12\n" +
	"\x10_analysis_statusB\x10\n" +
	"\x0e_thumbnail_urlB\x16\n" +
	"\x14_hls_master_playlistB\r\n" +
	"\v_difficultyB\n" +
	"\n" +
	"\b_summaryB\x13\n" +
	"\x11_raw_subtitle_urlB\x0f\n" +
	"\r_published_atB\x14\n" +
	"\x12_visibility_status\x1a\xbf\x01\n" +
	"\fVideoDeleted\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\"\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\tH\x00R\tdeletedAt\x88\x01\x01\x12\x1f\n" +
	"\voccurred_at\x18\x04 \x01(\tR\n" +
	"occurredAt\x12\x1b\n" +
	"\x06reason\x18\x05 \x01(\tH\x01R\x06reason\x88\x01\x01B\r\n" +
	"\v_deleted_atB\t\n" +
	"\a_reason\x1a\xfd\x04\n" +
	"\x0fVideoMediaReady\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1f\n" +
	"\voccurred_at\x18\x03 \x01(\tR\n" +
	"occurredAt\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\fmedia_status\x18\x05 \x01(\tR\vmediaStatus\x12,\n" +
	"\x0fduration_micros\x18\x06 \x01(\x03H\x00R\x0edurationMicros\x88\x01\x01\x122\n" +
	"\x12encoded_resolution\x18\a \x01(\tH\x01R\x11encodedResolution\x88\x01\x01\x12,\n" +
	"\x0fencoded_bitrate\x18\b \x01(\x05H\x02R\x0eencodedBitrate\x88\x01\x01\x12(\n" +
	"\rthumbnail_url\x18\t \x01(\tH\x03R\fthumbnailUrl\x88\x01\x01\x123\n" +
	"\x13hls_master_playlist\x18\n" +
	" \x01(\tH\x04R\x11hlsMasterPlaylist\x88\x01\x01\x12\x1a\n" +
	"\x06job_id\x18\v \x01(\tH\x05R\x05jobId\x88\x01\x01\x12\"\n" +
	"\n" +
	"emitted_at\x18\f \x01(\tH\x06R\temittedAt\x88\x01\x01\x12'\n" +
	"\x0fanalysis_status\x18\r \x01(\tR\x0eanalysisStatusB\x12\n" +
	"\x10_duration_microsB\x15\n" +
	"\x13_encoded_resolutionB\x12\n" +
	"\x10_encoded_bitrateB\x10\n" +
	"\x0e_thumbnail_urlB\x16\n" +
	"\x14_hls_master_playlistB\t\n" +
	"\a_job_idB\r\n" +
	"\v_emitted_at\x1a\x98\x04\n" +
	"\x0fVideoAIEnriched\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1f\n" +
	"\voccurred_at\x18\x03 \x01(\tR\n" +
	"occurredAt\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12'\n" +
	"\x0fanalysis_status\x18\x05 \x01(\tR\x0eanalysisStatus\x12#\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\tH\x00R\n" +
	"difficulty\x88\x01\x01\x12\x1d\n" +
	"\asummary\x18\a \x01(\tH\x01R\asummary\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12-\n" +
	"\x10raw_subtitle_url\x18\t \x01(\tH\x02R\x0erawSubtitleUrl\x88\x01\x01\x12\x1a\n" +
	"\x06job_id\x18\n" +
	" \x01(\tH\x03R\x05jobId\x88\x01\x01\x12\"\n" +
	"\n" +
	"emitted_at\x18\v \x01(\tH\x04R\temittedAt\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\f \x01(\tH\x05R\ferrorMessage\x88\x01\x01\x12!\n" +
	"\fmedia_status\x18\r \x01(\tR\vmediaStatusB\r\n" +
	"\v_difficultyB\n" +
	"\n" +
	"\b_summaryB\x13\n" +
	"\x11_raw_subtitle_urlB\t\n" +
	"\a_job_idB\r\n" +
	"\v_emitted_atB\x10\n" +
	"\x0e_error_message\x1a\x8a\x03\n" +
	"\x15VideoProcessingFailed\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1f\n" +
	"\voccurred_at\x18\x03 \x01(\tR\n" +
	"occurredAt\x12!\n" +
	"\ffailed_stage\x18\x04 \x01(\tR\vfailedStage\x12(\n" +
	"\rerror_message\x18\x05 \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x12\x1a\n" +
	"\x06job_id\x18\x06 \x01(\tH\x01R\x05jobId\x88\x01\x01\x12\"\n" +
	"\n" +
	"emitted_at\x18\a \x01(\tH\x02R\temittedAt\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12!\n" +
	"\fmedia_status\x18\t \x01(\tR\vmediaStatus\x12'\n" +
	"\x0fanalysis_status\x18\n" +
	" \x01(\tR\x0eanalysisStatusB\x10\n" +
	"\x0e_error_messageB\t\n" +
	"\a_job_idB\r\n" +
	"\v_emitted_at\x1a\xfd\x02\n" +
	"\x16VideoVisibilityChanged\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1f\n" +
	"\voccurred_at\x18\x03 \x01(\tR\n" +
	"occurredAt\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12,\n" +
	"\x0fprevious_status\x18\x05 \x01(\tH\x00R\x0epreviousStatus\x88\x01\x01\x12&\n" +
	"\fpublished_at\x18\x06 \x01(\tH\x01R\vpublishedAt\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\a \x01(\tH\x02R\x06reason\x88\x01\x01\x120\n" +
	"\x11visibility_status\x18\n" +
	" \x01(\tH\x03R\x10visibilityStatus\x88\x01\x01B\x12\n" +
	"\x10_previous_statusB\x0f\n" +
	"\r_published_atB\t\n" +
	"\a_reasonB\x14\n" +
	"\x12_visibility_statusJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"B\t\n" +
	"\apayload*\x96\x02\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EVENT_TYPE_VIDEO_CREATED\x10\x01\x12\x1c\n" +
	"\x18EVENT_TYPE_VIDEO_UPDATED\x10\x02\x12\x1c\n" +
	"\x18EVENT_TYPE_VIDEO_DELETED\x10\x03\x12 \n" +
	"\x1cEVENT_TYPE_VIDEO_MEDIA_READY\x10\x04\x12 \n" +
	"\x1cEVENT_TYPE_VIDEO_AI_ENRICHED\x10\x05\x12&\n" +
	"\"EVENT_TYPE_VIDEO_PROCESSING_FAILED\x10\x06\x12'\n" +
	"#EVENT_TYPE_VIDEO_VISIBILITY_CHANGED\x10\aBDZBgithub.com/bionicotaku/lingo-services-catalog/api/video/v1;videov1b\x06proto3"

var (
	file_api_video_v1_events_proto_rawDescOnce sync.Once
	file_api_video_v1_events_proto_rawDescData []byte
)

func file_api_video_v1_events_proto_rawDescGZIP() []byte {
	file_api_video_v1_events_proto_rawDescOnce.Do(func() {
		file_api_video_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_video_v1_events_proto_rawDesc), len(file_api_video_v1_events_proto_rawDesc)))
	})
	return file_api_video_v1_events_proto_rawDescData
}

var file_api_video_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_video_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_video_v1_events_proto_goTypes = []any{
	(EventType)(0),                       // 0: video.v1.EventType
	(*Event)(nil),                        // 1: video.v1.Event
	(*Event_VideoCreated)(nil),           // 2: video.v1.Event.VideoCreated
	(*Event_VideoUpdated)(nil),           // 3: video.v1.Event.VideoUpdated
	(*Event_VideoDeleted)(nil),           // 4: video.v1.Event.VideoDeleted
	(*Event_VideoMediaReady)(nil),        // 5: video.v1.Event.VideoMediaReady
	(*Event_VideoAIEnriched)(nil),        // 6: video.v1.Event.VideoAIEnriched
	(*Event_VideoProcessingFailed)(nil),  // 7: video.v1.Event.VideoProcessingFailed
	(*Event_VideoVisibilityChanged)(nil), // 8: video.v1.Event.VideoVisibilityChanged
}
var file_api_video_v1_events_proto_depIdxs = []int32{
	0, // 0: video.v1.Event.event_type:type_name -> video.v1.EventType
	2, // 1: video.v1.Event.created:type_name -> video.v1.Event.VideoCreated
	3, // 2: video.v1.Event.updated:type_name -> video.v1.Event.VideoUpdated
	4, // 3: video.v1.Event.deleted:type_name -> video.v1.Event.VideoDeleted
	5, // 4: video.v1.Event.media_ready:type_name -> video.v1.Event.VideoMediaReady
	6, // 5: video.v1.Event.ai_enriched:type_name -> video.v1.Event.VideoAIEnriched
	7, // 6: video.v1.Event.processing_failed:type_name -> video.v1.Event.VideoProcessingFailed
	8, // 7: video.v1.Event.visibility_changed:type_name -> video.v1.Event.VideoVisibilityChanged
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_video_v1_events_proto_init() }
func file_api_video_v1_events_proto_init() {
	if File_api_video_v1_events_proto != nil {
		return
	}
	file_api_video_v1_events_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_Created)(nil),
		(*Event_Updated)(nil),
		(*Event_Deleted)(nil),
		(*Event_MediaReady)(nil),
		(*Event_AiEnriched)(nil),
		(*Event_ProcessingFailed)(nil),
		(*Event_VisibilityChanged)(nil),
	}
	file_api_video_v1_events_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_video_v1_events_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_video_v1_events_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_video_v1_events_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_video_v1_events_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_video_v1_events_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_video_v1_events_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_video_v1_events_proto_rawDesc), len(file_api_video_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_video_v1_events_proto_goTypes,
		DependencyIndexes: file_api_video_v1_events_proto_depIdxs,
		EnumInfos:         file_api_video_v1_events_proto_enumTypes,
		MessageInfos:      file_api_video_v1_events_proto_msgTypes,
	}.Build()
	File_api_video_v1_events_proto = out.File
	file_api_video_v1_events_proto_goTypes = nil
	file_api_video_v1_events_proto_depIdxs = nil
}
