// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/video/v1/lifecycle.proto

package videov1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessingStage int32

const (
	ProcessingStage_PROCESSING_STAGE_UNSPECIFIED ProcessingStage = 0
	ProcessingStage_PROCESSING_STAGE_MEDIA       ProcessingStage = 1
	ProcessingStage_PROCESSING_STAGE_ANALYSIS    ProcessingStage = 2
)

// Enum value maps for ProcessingStage.
var (
	ProcessingStage_name = map[int32]string{
		0: "PROCESSING_STAGE_UNSPECIFIED",
		1: "PROCESSING_STAGE_MEDIA",
		2: "PROCESSING_STAGE_ANALYSIS",
	}
	ProcessingStage_value = map[string]int32{
		"PROCESSING_STAGE_UNSPECIFIED": 0,
		"PROCESSING_STAGE_MEDIA":       1,
		"PROCESSING_STAGE_ANALYSIS":    2,
	}
)

func (x ProcessingStage) Enum() *ProcessingStage {
	p := new(ProcessingStage)
	*p = x
	return p
}

func (x ProcessingStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessingStage) Descriptor() protoreflect.EnumDescriptor {
	return file_api_video_v1_lifecycle_proto_enumTypes[0].Descriptor()
}

func (ProcessingStage) Type() protoreflect.EnumType {
	return &file_api_video_v1_lifecycle_proto_enumTypes[0]
}

func (x ProcessingStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessingStage.Descriptor instead.
func (ProcessingStage) EnumDescriptor() ([]byte, []int) {
	return file_api_video_v1_lifecycle_proto_rawDescGZIP(), []int{0}
}

type RegisterUploadRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UploadUserId     string                 `protobuf:"bytes,1,opt,name=upload_user_id,json=uploadUserId,proto3" json:"upload_user_id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description      *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	RawFileReference string                 `protobuf:"bytes,4,opt,name=raw_file_reference,json=rawFileReference,proto3" json:"raw_file_reference,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterUploadRequest) Reset() {
	*x = RegisterUploadRequest{}
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUploadRequest) ProtoMessage() {}

func (x *RegisterUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUploadRequest.ProtoReflect.Descriptor instead.
func (*RegisterUploadRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUploadRequest) GetUploadUserId() string {
	if x != nil {
		return x.UploadUserId
	}
	return ""
}

func (x *RegisterUploadRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RegisterUploadRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *RegisterUploadRequest) GetRawFileReference() string {
	if x != nil {
		return x.RawFileReference
	}
	return ""
}

type RegisterUploadResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	MediaStatus    string                 `protobuf:"bytes,3,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`
	AnalysisStatus string                 `protobuf:"bytes,4,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EventId        string                 `protobuf:"bytes,6,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Version        int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	OccurredAt     string                 `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterUploadResponse) Reset() {
	*x = RegisterUploadResponse{}
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUploadResponse) ProtoMessage() {}

func (x *RegisterUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUploadResponse.ProtoReflect.Descriptor instead.
func (*RegisterUploadResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUploadResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *RegisterUploadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterUploadResponse) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

func (x *RegisterUploadResponse) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

func (x *RegisterUploadResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RegisterUploadResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RegisterUploadResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RegisterUploadResponse) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

type UpdateOriginalMediaRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VideoId         string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	RawFileSize     *int64                 `protobuf:"varint,2,opt,name=raw_file_size,json=rawFileSize,proto3,oneof" json:"raw_file_size,omitempty"`
	RawResolution   *string                `protobuf:"bytes,3,opt,name=raw_resolution,json=rawResolution,proto3,oneof" json:"raw_resolution,omitempty"`
	RawBitrate      *int32                 `protobuf:"varint,4,opt,name=raw_bitrate,json=rawBitrate,proto3,oneof" json:"raw_bitrate,omitempty"`
	ExpectedVersion *int64                 `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateOriginalMediaRequest) Reset() {
	*x = UpdateOriginalMediaRequest{}
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOriginalMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOriginalMediaRequest) ProtoMessage() {}

func (x *UpdateOriginalMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOriginalMediaRequest.ProtoReflect.Descriptor instead.
func (*UpdateOriginalMediaRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_lifecycle_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateOriginalMediaRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *UpdateOriginalMediaRequest) GetRawFileSize() int64 {
	if x != nil && x.RawFileSize != nil {
		return *x.RawFileSize
	}
	return 0
}

func (x *UpdateOriginalMediaRequest) GetRawResolution() string {
	if x != nil && x.RawResolution != nil {
		return *x.RawResolution
	}
	return ""
}

func (x *UpdateOriginalMediaRequest) GetRawBitrate() int32 {
	if x != nil && x.RawBitrate != nil {
		return *x.RawBitrate
	}
	return 0
}

func (x *UpdateOriginalMediaRequest) GetExpectedVersion() int64 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

type UpdateProcessingStatusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VideoId         string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Stage           ProcessingStage        `protobuf:"varint,2,opt,name=stage,proto3,enum=video.v1.ProcessingStage" json:"stage,omitempty"`
	ExpectedStatus  *string                `protobuf:"bytes,3,opt,name=expected_status,json=expectedStatus,proto3,oneof" json:"expected_status,omitempty"`
	NewStatus       string                 `protobuf:"bytes,4,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	JobId           string                 `protobuf:"bytes,5,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	EmittedAt       string                 `protobuf:"bytes,6,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	ErrorMessage    *string                `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	ExpectedVersion *int64                 `protobuf:"varint,8,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateProcessingStatusRequest) Reset() {
	*x = UpdateProcessingStatusRequest{}
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProcessingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProcessingStatusRequest) ProtoMessage() {}

func (x *UpdateProcessingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProcessingStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateProcessingStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_lifecycle_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProcessingStatusRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *UpdateProcessingStatusRequest) GetStage() ProcessingStage {
	if x != nil {
		return x.Stage
	}
	return ProcessingStage_PROCESSING_STAGE_UNSPECIFIED
}

func (x *UpdateProcessingStatusRequest) GetExpectedStatus() string {
	if x != nil && x.ExpectedStatus != nil {
		return *x.ExpectedStatus
	}
	return ""
}

func (x *UpdateProcessingStatusRequest) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *UpdateProcessingStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UpdateProcessingStatusRequest) GetEmittedAt() string {
	if x != nil {
		return x.EmittedAt
	}
	return ""
}

func (x *UpdateProcessingStatusRequest) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *UpdateProcessingStatusRequest) GetExpectedVersion() int64 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

type UpdateMediaInfoRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VideoId           string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	DurationMicros    *int64                 `protobuf:"varint,2,opt,name=duration_micros,json=durationMicros,proto3,oneof" json:"duration_micros,omitempty"`
	EncodedResolution *string                `protobuf:"bytes,3,opt,name=encoded_resolution,json=encodedResolution,proto3,oneof" json:"encoded_resolution,omitempty"`
	EncodedBitrate    *int32                 `protobuf:"varint,4,opt,name=encoded_bitrate,json=encodedBitrate,proto3,oneof" json:"encoded_bitrate,omitempty"`
	ThumbnailUrl      *string                `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	HlsMasterPlaylist *string                `protobuf:"bytes,6,opt,name=hls_master_playlist,json=hlsMasterPlaylist,proto3,oneof" json:"hls_master_playlist,omitempty"`
	MediaStatus       *string                `protobuf:"bytes,7,opt,name=media_status,json=mediaStatus,proto3,oneof" json:"media_status,omitempty"`
	JobId             string                 `protobuf:"bytes,8,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	EmittedAt         string                 `protobuf:"bytes,9,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	ExpectedVersion   *int64                 `protobuf:"varint,10,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateMediaInfoRequest) Reset() {
	*x = UpdateMediaInfoRequest{}
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaInfoRequest) ProtoMessage() {}

func (x *UpdateMediaInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMediaInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateMediaInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_lifecycle_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMediaInfoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *UpdateMediaInfoRequest) GetDurationMicros() int64 {
	if x != nil && x.DurationMicros != nil {
		return *x.DurationMicros
	}
	return 0
}

func (x *UpdateMediaInfoRequest) GetEncodedResolution() string {
	if x != nil && x.EncodedResolution != nil {
		return *x.EncodedResolution
	}
	return ""
}

func (x *UpdateMediaInfoRequest) GetEncodedBitrate() int32 {
	if x != nil && x.EncodedBitrate != nil {
		return *x.EncodedBitrate
	}
	return 0
}

func (x *UpdateMediaInfoRequest) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *UpdateMediaInfoRequest) GetHlsMasterPlaylist() string {
	if x != nil && x.HlsMasterPlaylist != nil {
		return *x.HlsMasterPlaylist
	}
	return ""
}

func (x *UpdateMediaInfoRequest) GetMediaStatus() string {
	if x != nil && x.MediaStatus != nil {
		return *x.MediaStatus
	}
	return ""
}

func (x *UpdateMediaInfoRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UpdateMediaInfoRequest) GetEmittedAt() string {
	if x != nil {
		return x.EmittedAt
	}
	return ""
}

func (x *UpdateMediaInfoRequest) GetExpectedVersion() int64 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

type UpdateAIAttributesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VideoId         string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Difficulty      *string                `protobuf:"bytes,2,opt,name=difficulty,proto3,oneof" json:"difficulty,omitempty"`
	Summary         *string                `protobuf:"bytes,3,opt,name=summary,proto3,oneof" json:"summary,omitempty"`
	Tags            []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	RawSubtitleUrl  *string                `protobuf:"bytes,5,opt,name=raw_subtitle_url,json=rawSubtitleUrl,proto3,oneof" json:"raw_subtitle_url,omitempty"`
	ErrorMessage    *string                `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	AnalysisStatus  *string                `protobuf:"bytes,7,opt,name=analysis_status,json=analysisStatus,proto3,oneof" json:"analysis_status,omitempty"`
	JobId           string                 `protobuf:"bytes,8,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	EmittedAt       string                 `protobuf:"bytes,9,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	ExpectedVersion *int64                 `protobuf:"varint,10,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateAIAttributesRequest) Reset() {
	*x = UpdateAIAttributesRequest{}
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAIAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAIAttributesRequest) ProtoMessage() {}

func (x *UpdateAIAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAIAttributesRequest.ProtoReflect.Descriptor instead.
func (*UpdateAIAttributesRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_lifecycle_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAIAttributesRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *UpdateAIAttributesRequest) GetDifficulty() string {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return ""
}

func (x *UpdateAIAttributesRequest) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

func (x *UpdateAIAttributesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateAIAttributesRequest) GetRawSubtitleUrl() string {
	if x != nil && x.RawSubtitleUrl != nil {
		return *x.RawSubtitleUrl
	}
	return ""
}

func (x *UpdateAIAttributesRequest) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *UpdateAIAttributesRequest) GetAnalysisStatus() string {
	if x != nil && x.AnalysisStatus != nil {
		return *x.AnalysisStatus
	}
	return ""
}

func (x *UpdateAIAttributesRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UpdateAIAttributesRequest) GetEmittedAt() string {
	if x != nil {
		return x.EmittedAt
	}
	return ""
}

func (x *UpdateAIAttributesRequest) GetExpectedVersion() int64 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

type ArchiveVideoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VideoId         string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Reason          *string                `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	ExpectedVersion *int64                 `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ArchiveVideoRequest) Reset() {
	*x = ArchiveVideoRequest{}
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveVideoRequest) ProtoMessage() {}

func (x *ArchiveVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveVideoRequest.ProtoReflect.Descriptor instead.
func (*ArchiveVideoRequest) Descriptor() ([]byte, []int) {
	return file_api_video_v1_lifecycle_proto_rawDescGZIP(), []int{6}
}

func (x *ArchiveVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *ArchiveVideoRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *ArchiveVideoRequest) GetExpectedVersion() int64 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

type VideoRevision struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	MediaStatus    string                 `protobuf:"bytes,3,opt,name=media_status,json=mediaStatus,proto3" json:"media_status,omitempty"`
	AnalysisStatus string                 `protobuf:"bytes,4,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"`
	Version        int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EventId        string                 `protobuf:"bytes,7,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt     string                 `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoRevision) Reset() {
	*x = VideoRevision{}
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRevision) ProtoMessage() {}

func (x *VideoRevision) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRevision.ProtoReflect.Descriptor instead.
func (*VideoRevision) Descriptor() ([]byte, []int) {
	return file_api_video_v1_lifecycle_proto_rawDescGZIP(), []int{7}
}

func (x *VideoRevision) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoRevision) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VideoRevision) GetMediaStatus() string {
	if x != nil {
		return x.MediaStatus
	}
	return ""
}

func (x *VideoRevision) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

func (x *VideoRevision) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VideoRevision) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *VideoRevision) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *VideoRevision) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

type UpdateOriginalMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      *VideoRevision         `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOriginalMediaResponse) Reset() {
	*x = UpdateOriginalMediaResponse{}
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOriginalMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOriginalMediaResponse) ProtoMessage() {}

func (x *UpdateOriginalMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOriginalMediaResponse.ProtoReflect.Descriptor instead.
func (*UpdateOriginalMediaResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_lifecycle_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateOriginalMediaResponse) GetRevision() *VideoRevision {
	if x != nil {
		return x.Revision
	}
	return nil
}

type UpdateProcessingStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      *VideoRevision         `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProcessingStatusResponse) Reset() {
	*x = UpdateProcessingStatusResponse{}
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProcessingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProcessingStatusResponse) ProtoMessage() {}

func (x *UpdateProcessingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProcessingStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateProcessingStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_lifecycle_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProcessingStatusResponse) GetRevision() *VideoRevision {
	if x != nil {
		return x.Revision
	}
	return nil
}

type UpdateMediaInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      *VideoRevision         `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMediaInfoResponse) Reset() {
	*x = UpdateMediaInfoResponse{}
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaInfoResponse) ProtoMessage() {}

func (x *UpdateMediaInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMediaInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateMediaInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_lifecycle_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMediaInfoResponse) GetRevision() *VideoRevision {
	if x != nil {
		return x.Revision
	}
	return nil
}

type UpdateAIAttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      *VideoRevision         `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAIAttributesResponse) Reset() {
	*x = UpdateAIAttributesResponse{}
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAIAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAIAttributesResponse) ProtoMessage() {}

func (x *UpdateAIAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAIAttributesResponse.ProtoReflect.Descriptor instead.
func (*UpdateAIAttributesResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_lifecycle_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateAIAttributesResponse) GetRevision() *VideoRevision {
	if x != nil {
		return x.Revision
	}
	return nil
}

type ArchiveVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      *VideoRevision         `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveVideoResponse) Reset() {
	*x = ArchiveVideoResponse{}
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveVideoResponse) ProtoMessage() {}

func (x *ArchiveVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_v1_lifecycle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveVideoResponse.ProtoReflect.Descriptor instead.
func (*ArchiveVideoResponse) Descriptor() ([]byte, []int) {
	return file_api_video_v1_lifecycle_proto_rawDescGZIP(), []int{12}
}

func (x *ArchiveVideoResponse) GetRevision() *VideoRevision {
	if x != nil {
		return x.Revision
	}
	return nil
}

var File_api_video_v1_lifecycle_proto protoreflect.FileDescriptor

const file_api_video_v1_lifecycle_proto_rawDesc = "" +
	"\n" +
	"\x1capi/video/v1/lifecycle.proto\x12\bvideo.v1\x1a\x1bbuf/validate/validate.proto\"\xd4\x01\n" +
	"\x15RegisterUploadRequest\x12.\n" +
	"\x0eupload_user_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\fuploadUserId\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x125\n" +
	"\x12raw_file_reference\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x10rawFileReferenceB\x0e\n" +
	"\f_description\"\x8c\x02\n" +
	"\x16RegisterUploadResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fmedia_status\x18\x03 \x01(\tR\vmediaStatus\x12'\n" +
	"\x0fanalysis_status\x18\x04 \x01(\tR\x0eanalysisStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x19\n" +
	"\bevent_id\x18\x06 \x01(\tR\aeventId\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12\x1f\n" +
	"\voccurred_at\x18\b \x01(\tR\n" +
	"occurredAt\"\xd1\x02\n" +
	"\x1aUpdateOriginalMediaRequest\x12#\n" +
	"\bvideo_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\avideoId\x120\n" +
	"\rraw_file_size\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02 \x00H\x00R\vrawFileSize\x88\x01\x01\x12*\n" +
	"\x0eraw_resolution\x18\x03 \x01(\tH\x01R\rrawResolution\x88\x01\x01\x12-\n" +
	"\vraw_bitrate\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00H\x02R\n" +
	"rawBitrate\x88\x01\x01\x127\n" +
	"\x10expected_version\x18\x05 \x01(\x03B\a\xbaH\x04\"\x02 \x00H\x03R\x0fexpectedVersion\x88\x01\x01B\x10\n" +
	"\x0e_raw_file_sizeB\x11\n" +
	"\x0f_raw_resolutionB\x0e\n" +
	"\f_raw_bitrateB\x13\n" +
	"\x11_expected_version\"\xbb\x03\n" +
	"\x1dUpdateProcessingStatusRequest\x12#\n" +
	"\bvideo_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\avideoId\x129\n" +
	"\x05stage\x18\x02 \x01(\x0e2\x19.video.v1.ProcessingStageB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05stage\x12,\n" +
	"\x0fexpected_status\x18\x03 \x01(\tH\x00R\x0eexpectedStatus\x88\x01\x01\x12&\n" +
	"\n" +
	"new_status\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tnewStatus\x12\x1e\n" +
	"\x06job_id\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05jobId\x12&\n" +
	"\n" +
	"emitted_at\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\temittedAt\x12(\n" +
	"\rerror_message\x18\a \x01(\tH\x01R\ferrorMessage\x88\x01\x01\x127\n" +
	"\x10expected_version\x18\b \x01(\x03B\a\xbaH\x04\"\x02 \x00H\x02R\x0fexpectedVersion\x88\x01\x01B\x12\n" +
	"\x10_expected_statusB\x10\n" +
	"\x0e_error_messageB\x13\n" +
	"\x11_expected_version\"\xf6\x04\n" +
	"\x16UpdateMediaInfoRequest\x12#\n" +
	"\bvideo_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\avideoId\x125\n" +
	"\x0fduration_micros\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02(\x00H\x00R\x0edurationMicros\x88\x01\x01\x122\n" +
	"\x12encoded_resolution\x18\x03 \x01(\tH\x01R\x11encodedResolution\x88\x01\x01\x125\n" +
	"\x0fencoded_bitrate\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\x02R\x0eencodedBitrate\x88\x01\x01\x12(\n" +
	"\rthumbnail_url\x18\x05 \x01(\tH\x03R\fthumbnailUrl\x88\x01\x01\x123\n" +
	"\x13hls_master_playlist\x18\x06 \x01(\tH\x04R\x11hlsMasterPlaylist\x88\x01\x01\x12&\n" +
	"\fmedia_status\x18\a \x01(\tH\x05R\vmediaStatus\x88\x01\x01\x12\x1e\n" +
	"\x06job_id\x18\b \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05jobId\x12&\n" +
	"\n" +
	"emitted_at\x18\t \x01(\tB\a\xbaH\x04r\x02\x10\x01R\temittedAt\x127\n" +
	"\x10expected_version\x18\n" +
	" \x01(\x03B\a\xbaH\x04\"\x02 \x00H\x06R\x0fexpectedVersion\x88\x01\x01B\x12\n" +
	"\x10_duration_microsB\x15\n" +
	"\x13_encoded_resolutionB\x12\n" +
	"\x10_encoded_bitrateB\x10\n" +
	"\x0e_thumbnail_urlB\x16\n" +
	"\x14_hls_master_playlistB\x0f\n" +
	"\r_media_statusB\x13\n" +
	"\x11_expected_version\"\x8b\x04\n" +
	"\x19UpdateAIAttributesRequest\x12#\n" +
	"\bvideo_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\avideoId\x12#\n" +
	"\n" +
	"difficulty\x18\x02 \x01(\tH\x00R\n" +
	"difficulty\x88\x01\x01\x12\x1d\n" +
	"\asummary\x18\x03 \x01(\tH\x01R\asummary\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12-\n" +
	"\x10raw_subtitle_url\x18\x05 \x01(\tH\x02R\x0erawSubtitleUrl\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x06 \x01(\tH\x03R\ferrorMessage\x88\x01\x01\x12,\n" +
	"\x0fanalysis_status\x18\a \x01(\tH\x04R\x0eanalysisStatus\x88\x01\x01\x12\x1e\n" +
	"\x06job_id\x18\b \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05jobId\x12&\n" +
	"\n" +
	"emitted_at\x18\t \x01(\tB\a\xbaH\x04r\x02\x10\x01R\temittedAt\x127\n" +
	"\x10expected_version\x18\n" +
	" \x01(\x03B\a\xbaH\x04\"\x02 \x00H\x05R\x0fexpectedVersion\x88\x01\x01B\r\n" +
	"\v_difficultyB\n" +
	"\n" +
	"\b_summaryB\x13\n" +
	"\x11_raw_subtitle_urlB\x10\n" +
	"\x0e_error_messageB\x12\n" +
	"\x10_analysis_statusB\x13\n" +
	"\x11_expected_version\"\xb0\x01\n" +
	"\x13ArchiveVideoRequest\x12#\n" +
	"\bvideo_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\avideoId\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01\x127\n" +
	"\x10expected_version\x18\x03 \x01(\x03B\a\xbaH\x04\"\x02 \x00H\x01R\x0fexpectedVersion\x88\x01\x01B\t\n" +
	"\a_reasonB\x13\n" +
	"\x11_expected_version\"\x83\x02\n" +
	"\rVideoRevision\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fmedia_status\x18\x03 \x01(\tR\vmediaStatus\x12'\n" +
	"\x0fanalysis_status\x18\x04 \x01(\tR\x0eanalysisStatus\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x19\n" +
	"\bevent_id\x18\a \x01(\tR\aeventId\x12\x1f\n" +
	"\voccurred_at\x18\b \x01(\tR\n" +
	"occurredAt\"R\n" +
	"\x1bUpdateOriginalMediaResponse\x123\n" +
	"\brevision\x18\x01 \x01(\v2\x17.video.v1.VideoRevisionR\brevision\"U\n" +
	"\x1eUpdateProcessingStatusResponse\x123\n" +
	"\brevision\x18\x01 \x01(\v2\x17.video.v1.VideoRevisionR\brevision\"N\n" +
	"\x17UpdateMediaInfoResponse\x123\n" +
	"\brevision\x18\x01 \x01(\v2\x17.video.v1.VideoRevisionR\brevision\"Q\n" +
	"\x1aUpdateAIAttributesResponse\x123\n" +
	"\brevision\x18\x01 \x01(\v2\x17.video.v1.VideoRevisionR\brevision\"K\n" +
	"\x14ArchiveVideoResponse\x123\n" +
	"\brevision\x18\x01 \x01(\v2\x17.video.v1.VideoRevisionR\brevision*n\n" +
	"\x0fProcessingStage\x12 \n" +
	"\x1cPROCESSING_STAGE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PROCESSING_STAGE_MEDIA\x10\x01\x12\x1d\n" +
	"\x19PROCESSING_STAGE_ANALYSIS\x10\x022\xc7\x04\n" +
	"\x17CatalogLifecycleService\x12S\n" +
	"\x0eRegisterUpload\x12\x1f.video.v1.RegisterUploadRequest\x1a .video.v1.RegisterUploadResponse\x12b\n" +
	"\x13UpdateOriginalMedia\x12$.video.v1.UpdateOriginalMediaRequest\x1a%.video.v1.UpdateOriginalMediaResponse\x12k\n" +
	"\x16UpdateProcessingStatus\x12'.video.v1.UpdateProcessingStatusRequest\x1a(.video.v1.UpdateProcessingStatusResponse\x12V\n" +
	"\x0fUpdateMediaInfo\x12 .video.v1.UpdateMediaInfoRequest\x1a!.video.v1.UpdateMediaInfoResponse\x12_\n" +
	"\x12UpdateAIAttributes\x12#.video.v1.UpdateAIAttributesRequest\x1a$.video.v1.UpdateAIAttributesResponse\x12M\n" +
	"\fArchiveVideo\x12\x1d.video.v1.ArchiveVideoRequest\x1a\x1e.video.v1.ArchiveVideoResponseBDZBgithub.com/bionicotaku/lingo-services-catalog/api/video/v1;videov1b\x06proto3"

var (
	file_api_video_v1_lifecycle_proto_rawDescOnce sync.Once
	file_api_video_v1_lifecycle_proto_rawDescData []byte
)

func file_api_video_v1_lifecycle_proto_rawDescGZIP() []byte {
	file_api_video_v1_lifecycle_proto_rawDescOnce.Do(func() {
		file_api_video_v1_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_video_v1_lifecycle_proto_rawDesc), len(file_api_video_v1_lifecycle_proto_rawDesc)))
	})
	return file_api_video_v1_lifecycle_proto_rawDescData
}

var file_api_video_v1_lifecycle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_video_v1_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_video_v1_lifecycle_proto_goTypes = []any{
	(ProcessingStage)(0),                   // 0: video.v1.ProcessingStage
	(*RegisterUploadRequest)(nil),          // 1: video.v1.RegisterUploadRequest
	(*RegisterUploadResponse)(nil),         // 2: video.v1.RegisterUploadResponse
	(*UpdateOriginalMediaRequest)(nil),     // 3: video.v1.UpdateOriginalMediaRequest
	(*UpdateProcessingStatusRequest)(nil),  // 4: video.v1.UpdateProcessingStatusRequest
	(*UpdateMediaInfoRequest)(nil),         // 5: video.v1.UpdateMediaInfoRequest
	(*UpdateAIAttributesRequest)(nil),      // 6: video.v1.UpdateAIAttributesRequest
	(*ArchiveVideoRequest)(nil),            // 7: video.v1.ArchiveVideoRequest
	(*VideoRevision)(nil),                  // 8: video.v1.VideoRevision
	(*UpdateOriginalMediaResponse)(nil),    // 9: video.v1.UpdateOriginalMediaResponse
	(*UpdateProcessingStatusResponse)(nil), // 10: video.v1.UpdateProcessingStatusResponse
	(*UpdateMediaInfoResponse)(nil),        // 11: video.v1.UpdateMediaInfoResponse
	(*UpdateAIAttributesResponse)(nil),     // 12: video.v1.UpdateAIAttributesResponse
	(*ArchiveVideoResponse)(nil),           // 13: video.v1.ArchiveVideoResponse
}
var file_api_video_v1_lifecycle_proto_depIdxs = []int32{
	0,  // 0: video.v1.UpdateProcessingStatusRequest.stage:type_name -> video.v1.ProcessingStage
	8,  // 1: video.v1.UpdateOriginalMediaResponse.revision:type_name -> video.v1.VideoRevision
	8,  // 2: video.v1.UpdateProcessingStatusResponse.revision:type_name -> video.v1.VideoRevision
	8,  // 3: video.v1.UpdateMediaInfoResponse.revision:type_name -> video.v1.VideoRevision
	8,  // 4: video.v1.UpdateAIAttributesResponse.revision:type_name -> video.v1.VideoRevision
	8,  // 5: video.v1.ArchiveVideoResponse.revision:type_name -> video.v1.VideoRevision
	1,  // 6: video.v1.CatalogLifecycleService.RegisterUpload:input_type -> video.v1.RegisterUploadRequest
	3,  // 7: video.v1.CatalogLifecycleService.UpdateOriginalMedia:input_type -> video.v1.UpdateOriginalMediaRequest
	4,  // 8: video.v1.CatalogLifecycleService.UpdateProcessingStatus:input_type -> video.v1.UpdateProcessingStatusRequest
	5,  // 9: video.v1.CatalogLifecycleService.UpdateMediaInfo:input_type -> video.v1.UpdateMediaInfoRequest
	6,  // 10: video.v1.CatalogLifecycleService.UpdateAIAttributes:input_type -> video.v1.UpdateAIAttributesRequest
	7,  // 11: video.v1.CatalogLifecycleService.ArchiveVideo:input_type -> video.v1.ArchiveVideoRequest
	2,  // 12: video.v1.CatalogLifecycleService.RegisterUpload:output_type -> video.v1.RegisterUploadResponse
	9,  // 13: video.v1.CatalogLifecycleService.UpdateOriginalMedia:output_type -> video.v1.UpdateOriginalMediaResponse
	10, // 14: video.v1.CatalogLifecycleService.UpdateProcessingStatus:output_type -> video.v1.UpdateProcessingStatusResponse
	11, // 15: video.v1.CatalogLifecycleService.UpdateMediaInfo:output_type -> video.v1.UpdateMediaInfoResponse
	12, // 16: video.v1.CatalogLifecycleService.UpdateAIAttributes:output_type -> video.v1.UpdateAIAttributesResponse
	13, // 17: video.v1.CatalogLifecycleService.ArchiveVideo:output_type -> video.v1.ArchiveVideoResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_video_v1_lifecycle_proto_init() }
func file_api_video_v1_lifecycle_proto_init() {
	if File_api_video_v1_lifecycle_proto != nil {
		return
	}
	file_api_video_v1_lifecycle_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_video_v1_lifecycle_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_video_v1_lifecycle_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_video_v1_lifecycle_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_video_v1_lifecycle_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_video_v1_lifecycle_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_video_v1_lifecycle_proto_rawDesc), len(file_api_video_v1_lifecycle_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_video_v1_lifecycle_proto_goTypes,
		DependencyIndexes: file_api_video_v1_lifecycle_proto_depIdxs,
		EnumInfos:         file_api_video_v1_lifecycle_proto_enumTypes,
		MessageInfos:      file_api_video_v1_lifecycle_proto_msgTypes,
	}.Build()
	File_api_video_v1_lifecycle_proto = out.File
	file_api_video_v1_lifecycle_proto_goTypes = nil
	file_api_video_v1_lifecycle_proto_depIdxs = nil
}
