// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"fmt"

	"github.com/bionicotaku/lingo-services-profile/internal/infrastructure/configloader"
	"github.com/bionicotaku/lingo-services-profile/internal/repositories"
	"github.com/bionicotaku/lingo-services-profile/internal/tasks/engagement"
	"github.com/bionicotaku/lingo-utils/gclog"
	"github.com/bionicotaku/lingo-utils/pgxpoolx"
	"github.com/bionicotaku/lingo-utils/txmanager"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func wireEngagementTask(contextContext context.Context, params configloader.Params) (*engagementApp, func(), error) {
	runtimeConfig, err := configloader.LoadRuntimeConfig(params)
	if err != nil {
		return nil, nil, err
	}
	serviceInfo := configloader.ProvideServiceInfo(runtimeConfig)
	config := configloader.ProvideLoggerConfig(serviceInfo)
	component, cleanup, err := gclog.NewComponent(config)
	if err != nil {
		return nil, nil, err
	}
	logger := gclog.ProvideLogger(component)
	databaseConfig := configloader.ProvideDatabaseConfig(runtimeConfig)
	pgxpoolxConfig := configloader.ProvidePgxConfig(databaseConfig)
	pgxpoolxComponent, cleanup2, err := pgxpoolx.ProvideComponent(contextContext, pgxpoolxConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	pool := pgxpoolx.ProvidePool(pgxpoolxComponent)
	videoUserStatesRepository := repositories.NewVideoUserStatesRepository(pool, logger)
	txmanagerConfig := configloader.ProvideTxConfig(runtimeConfig)
	txmanagerComponent, cleanup3, err := txmanager.NewComponent(txmanagerConfig, pool, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	manager := txmanager.ProvideManager(txmanagerComponent)
	messagingConfig := configloader.ProvideMessagingConfig(runtimeConfig)
	outboxConfig := configloader.ProvideOutboxConfig(messagingConfig)
	inboxRepository := repositories.NewInboxRepository(pool, logger, outboxConfig)
	engagementPubSubConfig := configloader.ProvideEngagementConfig(messagingConfig)
	dependencies := configloader.ProvidePubSubDependencies(logger)
	engagementSubscriber, cleanup4, err := configloader.ProvideEngagementSubscriber(contextContext, engagementPubSubConfig, dependencies)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	runner := engagement.ProvideRunner(videoUserStatesRepository, inboxRepository, manager, engagementSubscriber, outboxConfig, logger)
	mainEngagementApp, err := newEngagementApp(logger, runner)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return mainEngagementApp, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func newEngagementApp(logger log.Logger, runner *engagement.Runner) (*engagementApp, error) {
	if runner == nil {
		return &engagementApp{Logger: logger}, nil
	}
	if logger == nil {
		return nil, fmt.Errorf("logger not initialized")
	}
	return &engagementApp{
		Runner: runner,
		Logger: logger,
	}, nil
}
