// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"github.com/bionicotaku/lingo-services-catalog/internal/controllers"
	"github.com/bionicotaku/lingo-services-catalog/internal/infrastructure/configloader"
	grpcserver "github.com/bionicotaku/lingo-services-catalog/internal/infrastructure/grpc_server"
	"github.com/bionicotaku/lingo-services-catalog/internal/repositories"
	"github.com/bionicotaku/lingo-services-catalog/internal/services"
	"github.com/bionicotaku/lingo-services-catalog/internal/tasks/engagement"
	"github.com/bionicotaku/lingo-services-catalog/internal/tasks/outbox"
	"github.com/bionicotaku/lingo-utils/gcjwt"
	"github.com/bionicotaku/lingo-utils/gclog"
	"github.com/bionicotaku/lingo-utils/gcpubsub"
	"github.com/bionicotaku/lingo-utils/observability"
	"github.com/bionicotaku/lingo-utils/pgxpoolx"
	"github.com/bionicotaku/lingo-utils/txmanager"
	"github.com/go-kratos/kratos/v2"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp 构建整个 Kratos 应用，分阶段装配依赖。
//
// Wire 会根据类型自动解析依赖关系并生成 wire_gen.go，详细的 Provider 列表见文件末尾注释。
//
// 依赖注入顺序:
//  1. 配置加载: configloader.ProviderSet 解析配置并派生组件配置
//  2. 基础设施: gclog → observability → gcjwt → pgxpoolx → txmanager
//  3. 业务层: repositories → services → controllers
//  4. 服务器: grpc_server.ProviderSet 组装 gRPC Server
//  5. 应用: newApp 创建 Kratos App
func wireApp(contextContext context.Context, params configloader.Params) (*kratos.App, func(), error) {
	runtimeConfig, err := configloader.LoadRuntimeConfig(params)
	if err != nil {
		return nil, nil, err
	}
	observabilityConfig := configloader.ProvideObservabilityConfig(runtimeConfig)
	serviceInfo := configloader.ProvideServiceInfo(runtimeConfig)
	observabilityServiceInfo := configloader.ProvideObservabilityInfo(serviceInfo)
	config := configloader.ProvideLoggerConfig(serviceInfo)
	component, cleanup, err := gclog.NewComponent(config)
	if err != nil {
		return nil, nil, err
	}
	logger := gclog.ProvideLogger(component)
	observabilityComponent, cleanup2, err := observability.NewComponent(contextContext, observabilityConfig, observabilityServiceInfo, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serverConfig := configloader.ProvideServerConfig(runtimeConfig)
	metricsConfig := observability.ProvideMetricsConfig(observabilityConfig)
	gcjwtConfig := configloader.ProvideJWTConfig(runtimeConfig)
	gcjwtComponent, cleanup3, err := gcjwt.NewComponent(gcjwtConfig, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	serverMiddleware, err := gcjwt.ProvideServerMiddleware(gcjwtComponent)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	databaseConfig := configloader.ProvideDatabaseConfig(runtimeConfig)
	pgxpoolxConfig := configloader.ProvidePgxConfig(databaseConfig)
	pgxpoolxComponent, cleanup4, err := pgxpoolx.ProvideComponent(contextContext, pgxpoolxConfig, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pool := pgxpoolx.ProvidePool(pgxpoolxComponent)
	videoRepository := repositories.NewVideoRepository(pool, logger)
	messagingConfig := configloader.ProvideMessagingConfig(runtimeConfig)
	configConfig := configloader.ProvideOutboxConfig(messagingConfig)
	outboxRepository := repositories.NewOutboxRepository(pool, logger, configConfig)
	inboxRepository := repositories.NewInboxRepository(pool, logger, configConfig)
	txmanagerConfig := configloader.ProvideTxConfig(runtimeConfig)
	txmanagerComponent, cleanup5, err := txmanager.NewComponent(txmanagerConfig, pool, logger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	manager := txmanager.ProvideManager(txmanagerComponent)
	lifecycleWriter := services.NewLifecycleWriter(videoRepository, outboxRepository, manager, logger)
	registerUploadService := services.NewRegisterUploadService(lifecycleWriter)
	originalMediaService := services.NewOriginalMediaService(lifecycleWriter, videoRepository)
	processingStatusService := services.NewProcessingStatusService(lifecycleWriter, videoRepository)
	mediaInfoService := services.NewMediaInfoService(lifecycleWriter, videoRepository)
	aiAttributesService := services.NewAIAttributesService(lifecycleWriter, videoRepository)
	visibilityService := services.NewVisibilityService(lifecycleWriter, videoRepository)
	lifecycleService := services.NewLifecycleService(registerUploadService, originalMediaService, processingStatusService, mediaInfoService, aiAttributesService, visibilityService)
	handlerTimeouts := configloader.ProvideHandlerTimeouts(runtimeConfig)
	baseHandler := controllers.NewBaseHandler(handlerTimeouts)
	lifecycleHandler := controllers.NewLifecycleHandler(lifecycleService, baseHandler)
	videoUserStatesRepository := repositories.NewVideoUserStatesRepository(pool, logger)
	videoQueryService := services.NewVideoQueryService(videoRepository, videoUserStatesRepository, manager, logger)
	videoQueryHandler := controllers.NewVideoQueryHandler(videoQueryService, baseHandler)
	server := grpcserver.NewGRPCServer(serverConfig, metricsConfig, serverMiddleware, lifecycleHandler, videoQueryHandler, logger)
	gcpubsubConfig := configloader.ProvidePubSubConfig(messagingConfig)
	dependencies := configloader.ProvidePubSubDependencies(logger)
	gcpubsubComponent, cleanup6, err := gcpubsub.NewComponent(contextContext, gcpubsubConfig, dependencies)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	publisher := gcpubsub.ProvidePublisher(gcpubsubComponent)
	runner := outbox.ProvideRunner(outboxRepository, publisher, gcpubsubConfig, configConfig, logger)
	engagementPubSubConfig := configloader.ProvideEngagementConfig(messagingConfig)
	engagementSubscriber, cleanup7, err := configloader.ProvideEngagementSubscriber(contextContext, engagementPubSubConfig, dependencies)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	engagementRunner := engagement.ProvideRunner(videoUserStatesRepository, inboxRepository, manager, engagementSubscriber, configConfig, logger)
	app := newApp(observabilityComponent, logger, server, serviceInfo, runner, engagementRunner)
	return app, func() {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
