// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: configs/conf.proto

package configpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Observability *Observability         `protobuf:"bytes,3,opt,name=observability,proto3" json:"observability,omitempty"`
	Messaging     *Messaging             `protobuf:"bytes,4,opt,name=messaging,proto3" json:"messaging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_configs_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetObservability() *Observability {
	if x != nil {
		return x.Observability
	}
	return nil
}

func (x *Bootstrap) GetMessaging() *Messaging {
	if x != nil {
		return x.Messaging
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          *Server_GRPC           `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Jwt           *Server_JWT            `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Handlers      *Server_Handlers       `protobuf:"bytes,3,opt,name=handlers,proto3" json:"handlers,omitempty"`
	MetadataKeys  []string               `protobuf:"bytes,4,rep,name=metadata_keys,json=metadataKeys,proto3" json:"metadata_keys,omitempty"` // 透传 header 列表，如 X-Apigateway-Api-Userinfo（actor 字段 Post-MVP 可追加）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_configs_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetJwt() *Server_JWT {
	if x != nil {
		return x.Jwt
	}
	return nil
}

func (x *Server) GetHandlers() *Server_Handlers {
	if x != nil {
		return x.Handlers
	}
	return nil
}

func (x *Server) GetMetadataKeys() []string {
	if x != nil {
		return x.MetadataKeys
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postgres      *Data_PostgreSQL       `protobuf:"bytes,1,opt,name=postgres,proto3" json:"postgres,omitempty"`
	GrpcClient    *Data_Client           `protobuf:"bytes,2,opt,name=grpc_client,json=grpcClient,proto3" json:"grpc_client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_configs_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetPostgres() *Data_PostgreSQL {
	if x != nil {
		return x.Postgres
	}
	return nil
}

func (x *Data) GetGrpcClient() *Data_Client {
	if x != nil {
		return x.GrpcClient
	}
	return nil
}

type Observability struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GlobalAttributes map[string]string      `protobuf:"bytes,1,rep,name=global_attributes,json=globalAttributes,proto3" json:"global_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tracing          *Observability_Tracing `protobuf:"bytes,2,opt,name=tracing,proto3" json:"tracing,omitempty"`
	Metrics          *Observability_Metrics `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Observability) Reset() {
	*x = Observability{}
	mi := &file_configs_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability) ProtoMessage() {}

func (x *Observability) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability.ProtoReflect.Descriptor instead.
func (*Observability) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Observability) GetGlobalAttributes() map[string]string {
	if x != nil {
		return x.GlobalAttributes
	}
	return nil
}

func (x *Observability) GetTracing() *Observability_Tracing {
	if x != nil {
		return x.Tracing
	}
	return nil
}

func (x *Observability) GetMetrics() *Observability_Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Messaging struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Pubsub *PubSub                `protobuf:"bytes,1,opt,name=pubsub,proto3" json:"pubsub,omitempty"`
	Outbox *OutboxPublisher       `protobuf:"bytes,2,opt,name=outbox,proto3" json:"outbox,omitempty"`
	Inbox  *InboxConsumer         `protobuf:"bytes,3,opt,name=inbox,proto3" json:"inbox,omitempty"`
	// Profile engagement Outbox 订阅配置（profile.engagement.* 事件）
	Engagement    *PubSub `protobuf:"bytes,4,opt,name=engagement,proto3" json:"engagement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Messaging) Reset() {
	*x = Messaging{}
	mi := &file_configs_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Messaging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Messaging) ProtoMessage() {}

func (x *Messaging) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Messaging.ProtoReflect.Descriptor instead.
func (*Messaging) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Messaging) GetPubsub() *PubSub {
	if x != nil {
		return x.Pubsub
	}
	return nil
}

func (x *Messaging) GetOutbox() *OutboxPublisher {
	if x != nil {
		return x.Outbox
	}
	return nil
}

func (x *Messaging) GetInbox() *InboxConsumer {
	if x != nil {
		return x.Inbox
	}
	return nil
}

func (x *Messaging) GetEngagement() *PubSub {
	if x != nil {
		return x.Engagement
	}
	return nil
}

type PubSub struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProjectId           string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TopicId             string                 `protobuf:"bytes,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	SubscriptionId      string                 `protobuf:"bytes,3,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	OrderingKeyEnabled  bool                   `protobuf:"varint,4,opt,name=ordering_key_enabled,json=orderingKeyEnabled,proto3" json:"ordering_key_enabled,omitempty"`
	LoggingEnabled      bool                   `protobuf:"varint,5,opt,name=logging_enabled,json=loggingEnabled,proto3" json:"logging_enabled,omitempty"`
	MetricsEnabled      bool                   `protobuf:"varint,6,opt,name=metrics_enabled,json=metricsEnabled,proto3" json:"metrics_enabled,omitempty"`
	EmulatorEndpoint    string                 `protobuf:"bytes,7,opt,name=emulator_endpoint,json=emulatorEndpoint,proto3" json:"emulator_endpoint,omitempty"`
	PublishTimeout      *durationpb.Duration   `protobuf:"bytes,8,opt,name=publish_timeout,json=publishTimeout,proto3" json:"publish_timeout,omitempty"`
	Receive             *Receive               `protobuf:"bytes,9,opt,name=receive,proto3" json:"receive,omitempty"`
	ExactlyOnceDelivery bool                   `protobuf:"varint,10,opt,name=exactly_once_delivery,json=exactlyOnceDelivery,proto3" json:"exactly_once_delivery,omitempty"`
	DeadLetterTopicId   string                 `protobuf:"bytes,11,opt,name=dead_letter_topic_id,json=deadLetterTopicId,proto3" json:"dead_letter_topic_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PubSub) Reset() {
	*x = PubSub{}
	mi := &file_configs_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubSub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSub) ProtoMessage() {}

func (x *PubSub) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSub.ProtoReflect.Descriptor instead.
func (*PubSub) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{5}
}

func (x *PubSub) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PubSub) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *PubSub) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *PubSub) GetOrderingKeyEnabled() bool {
	if x != nil {
		return x.OrderingKeyEnabled
	}
	return false
}

func (x *PubSub) GetLoggingEnabled() bool {
	if x != nil {
		return x.LoggingEnabled
	}
	return false
}

func (x *PubSub) GetMetricsEnabled() bool {
	if x != nil {
		return x.MetricsEnabled
	}
	return false
}

func (x *PubSub) GetEmulatorEndpoint() string {
	if x != nil {
		return x.EmulatorEndpoint
	}
	return ""
}

func (x *PubSub) GetPublishTimeout() *durationpb.Duration {
	if x != nil {
		return x.PublishTimeout
	}
	return nil
}

func (x *PubSub) GetReceive() *Receive {
	if x != nil {
		return x.Receive
	}
	return nil
}

func (x *PubSub) GetExactlyOnceDelivery() bool {
	if x != nil {
		return x.ExactlyOnceDelivery
	}
	return false
}

func (x *PubSub) GetDeadLetterTopicId() string {
	if x != nil {
		return x.DeadLetterTopicId
	}
	return ""
}

type Receive struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NumGoroutines          int32                  `protobuf:"varint,1,opt,name=num_goroutines,json=numGoroutines,proto3" json:"num_goroutines,omitempty"`
	MaxOutstandingMessages int32                  `protobuf:"varint,2,opt,name=max_outstanding_messages,json=maxOutstandingMessages,proto3" json:"max_outstanding_messages,omitempty"`
	MaxOutstandingBytes    int32                  `protobuf:"varint,3,opt,name=max_outstanding_bytes,json=maxOutstandingBytes,proto3" json:"max_outstanding_bytes,omitempty"`
	MaxExtension           *durationpb.Duration   `protobuf:"bytes,4,opt,name=max_extension,json=maxExtension,proto3" json:"max_extension,omitempty"`
	MaxExtensionPeriod     *durationpb.Duration   `protobuf:"bytes,5,opt,name=max_extension_period,json=maxExtensionPeriod,proto3" json:"max_extension_period,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Receive) Reset() {
	*x = Receive{}
	mi := &file_configs_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receive) ProtoMessage() {}

func (x *Receive) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receive.ProtoReflect.Descriptor instead.
func (*Receive) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Receive) GetNumGoroutines() int32 {
	if x != nil {
		return x.NumGoroutines
	}
	return 0
}

func (x *Receive) GetMaxOutstandingMessages() int32 {
	if x != nil {
		return x.MaxOutstandingMessages
	}
	return 0
}

func (x *Receive) GetMaxOutstandingBytes() int32 {
	if x != nil {
		return x.MaxOutstandingBytes
	}
	return 0
}

func (x *Receive) GetMaxExtension() *durationpb.Duration {
	if x != nil {
		return x.MaxExtension
	}
	return nil
}

func (x *Receive) GetMaxExtensionPeriod() *durationpb.Duration {
	if x != nil {
		return x.MaxExtensionPeriod
	}
	return nil
}

type OutboxPublisher struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BatchSize      int32                  `protobuf:"varint,1,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	TickInterval   *durationpb.Duration   `protobuf:"bytes,2,opt,name=tick_interval,json=tickInterval,proto3" json:"tick_interval,omitempty"`
	InitialBackoff *durationpb.Duration   `protobuf:"bytes,3,opt,name=initial_backoff,json=initialBackoff,proto3" json:"initial_backoff,omitempty"`
	MaxBackoff     *durationpb.Duration   `protobuf:"bytes,4,opt,name=max_backoff,json=maxBackoff,proto3" json:"max_backoff,omitempty"`
	MaxAttempts    int32                  `protobuf:"varint,5,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	PublishTimeout *durationpb.Duration   `protobuf:"bytes,6,opt,name=publish_timeout,json=publishTimeout,proto3" json:"publish_timeout,omitempty"`
	Workers        int32                  `protobuf:"varint,7,opt,name=workers,proto3" json:"workers,omitempty"`
	LockTtl        *durationpb.Duration   `protobuf:"bytes,8,opt,name=lock_ttl,json=lockTtl,proto3" json:"lock_ttl,omitempty"`
	LoggingEnabled *bool                  `protobuf:"varint,9,opt,name=logging_enabled,json=loggingEnabled,proto3,oneof" json:"logging_enabled,omitempty"`
	MetricsEnabled *bool                  `protobuf:"varint,10,opt,name=metrics_enabled,json=metricsEnabled,proto3,oneof" json:"metrics_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OutboxPublisher) Reset() {
	*x = OutboxPublisher{}
	mi := &file_configs_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboxPublisher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxPublisher) ProtoMessage() {}

func (x *OutboxPublisher) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxPublisher.ProtoReflect.Descriptor instead.
func (*OutboxPublisher) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{7}
}

func (x *OutboxPublisher) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *OutboxPublisher) GetTickInterval() *durationpb.Duration {
	if x != nil {
		return x.TickInterval
	}
	return nil
}

func (x *OutboxPublisher) GetInitialBackoff() *durationpb.Duration {
	if x != nil {
		return x.InitialBackoff
	}
	return nil
}

func (x *OutboxPublisher) GetMaxBackoff() *durationpb.Duration {
	if x != nil {
		return x.MaxBackoff
	}
	return nil
}

func (x *OutboxPublisher) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *OutboxPublisher) GetPublishTimeout() *durationpb.Duration {
	if x != nil {
		return x.PublishTimeout
	}
	return nil
}

func (x *OutboxPublisher) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *OutboxPublisher) GetLockTtl() *durationpb.Duration {
	if x != nil {
		return x.LockTtl
	}
	return nil
}

func (x *OutboxPublisher) GetLoggingEnabled() bool {
	if x != nil && x.LoggingEnabled != nil {
		return *x.LoggingEnabled
	}
	return false
}

func (x *OutboxPublisher) GetMetricsEnabled() bool {
	if x != nil && x.MetricsEnabled != nil {
		return *x.MetricsEnabled
	}
	return false
}

type InboxConsumer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceService  string                 `protobuf:"bytes,1,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	MaxConcurrency int32                  `protobuf:"varint,2,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	LoggingEnabled *bool                  `protobuf:"varint,3,opt,name=logging_enabled,json=loggingEnabled,proto3,oneof" json:"logging_enabled,omitempty"`
	MetricsEnabled *bool                  `protobuf:"varint,4,opt,name=metrics_enabled,json=metricsEnabled,proto3,oneof" json:"metrics_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InboxConsumer) Reset() {
	*x = InboxConsumer{}
	mi := &file_configs_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxConsumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxConsumer) ProtoMessage() {}

func (x *InboxConsumer) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxConsumer.ProtoReflect.Descriptor instead.
func (*InboxConsumer) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{8}
}

func (x *InboxConsumer) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *InboxConsumer) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *InboxConsumer) GetLoggingEnabled() bool {
	if x != nil && x.LoggingEnabled != nil {
		return *x.LoggingEnabled
	}
	return false
}

func (x *InboxConsumer) GetMetricsEnabled() bool {
	if x != nil && x.MetricsEnabled != nil {
		return *x.MetricsEnabled
	}
	return false
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_configs_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_JWT struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExpectedAudience string                 `protobuf:"bytes,1,opt,name=expected_audience,json=expectedAudience,proto3" json:"expected_audience,omitempty"`
	SkipValidate     bool                   `protobuf:"varint,2,opt,name=skip_validate,json=skipValidate,proto3" json:"skip_validate,omitempty"`
	Required         bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	HeaderKey        string                 `protobuf:"bytes,4,opt,name=header_key,json=headerKey,proto3" json:"header_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Server_JWT) Reset() {
	*x = Server_JWT{}
	mi := &file_configs_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_JWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_JWT) ProtoMessage() {}

func (x *Server_JWT) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_JWT.ProtoReflect.Descriptor instead.
func (*Server_JWT) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_JWT) GetExpectedAudience() string {
	if x != nil {
		return x.ExpectedAudience
	}
	return ""
}

func (x *Server_JWT) GetSkipValidate() bool {
	if x != nil {
		return x.SkipValidate
	}
	return false
}

func (x *Server_JWT) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Server_JWT) GetHeaderKey() string {
	if x != nil {
		return x.HeaderKey
	}
	return ""
}

type Server_Handlers struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DefaultTimeout *durationpb.Duration   `protobuf:"bytes,1,opt,name=default_timeout,json=defaultTimeout,proto3" json:"default_timeout,omitempty"`
	CommandTimeout *durationpb.Duration   `protobuf:"bytes,2,opt,name=command_timeout,json=commandTimeout,proto3" json:"command_timeout,omitempty"`
	QueryTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=query_timeout,json=queryTimeout,proto3" json:"query_timeout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Server_Handlers) Reset() {
	*x = Server_Handlers{}
	mi := &file_configs_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Handlers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Handlers) ProtoMessage() {}

func (x *Server_Handlers) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_Handlers.ProtoReflect.Descriptor instead.
func (*Server_Handlers) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Server_Handlers) GetDefaultTimeout() *durationpb.Duration {
	if x != nil {
		return x.DefaultTimeout
	}
	return nil
}

func (x *Server_Handlers) GetCommandTimeout() *durationpb.Duration {
	if x != nil {
		return x.CommandTimeout
	}
	return nil
}

func (x *Server_Handlers) GetQueryTimeout() *durationpb.Duration {
	if x != nil {
		return x.QueryTimeout
	}
	return nil
}

// PostgreSQL 数据库配置（Supabase 专用）
type Data_PostgreSQL struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DSN 连接串（必填）
	Dsn string `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	// 连接池配置
	MaxOpenConns      int32                `protobuf:"varint,2,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	MinOpenConns      int32                `protobuf:"varint,3,opt,name=min_open_conns,json=minOpenConns,proto3" json:"min_open_conns,omitempty"`
	MaxConnLifetime   *durationpb.Duration `protobuf:"bytes,4,opt,name=max_conn_lifetime,json=maxConnLifetime,proto3" json:"max_conn_lifetime,omitempty"`
	MaxConnIdleTime   *durationpb.Duration `protobuf:"bytes,5,opt,name=max_conn_idle_time,json=maxConnIdleTime,proto3" json:"max_conn_idle_time,omitempty"`
	HealthCheckPeriod *durationpb.Duration `protobuf:"bytes,6,opt,name=health_check_period,json=healthCheckPeriod,proto3" json:"health_check_period,omitempty"`
	// Supabase 特定配置
	Schema                    string                       `protobuf:"bytes,7,opt,name=schema,proto3" json:"schema,omitempty"`                                                                           // 默认 schema (如 "kratos_template")
	PreparedStatementsEnabled bool                         `protobuf:"varint,8,opt,name=prepared_statements_enabled,json=preparedStatementsEnabled,proto3" json:"prepared_statements_enabled,omitempty"` // Pooler 模式建议设为 false
	Transaction               *Data_PostgreSQL_Transaction `protobuf:"bytes,9,opt,name=transaction,proto3" json:"transaction,omitempty"`
	PoolMetricsEnabled        *bool                        `protobuf:"varint,10,opt,name=pool_metrics_enabled,json=poolMetricsEnabled,proto3,oneof" json:"pool_metrics_enabled,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Data_PostgreSQL) Reset() {
	*x = Data_PostgreSQL{}
	mi := &file_configs_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_PostgreSQL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_PostgreSQL) ProtoMessage() {}

func (x *Data_PostgreSQL) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_PostgreSQL.ProtoReflect.Descriptor instead.
func (*Data_PostgreSQL) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_PostgreSQL) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Data_PostgreSQL) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Data_PostgreSQL) GetMinOpenConns() int32 {
	if x != nil {
		return x.MinOpenConns
	}
	return 0
}

func (x *Data_PostgreSQL) GetMaxConnLifetime() *durationpb.Duration {
	if x != nil {
		return x.MaxConnLifetime
	}
	return nil
}

func (x *Data_PostgreSQL) GetMaxConnIdleTime() *durationpb.Duration {
	if x != nil {
		return x.MaxConnIdleTime
	}
	return nil
}

func (x *Data_PostgreSQL) GetHealthCheckPeriod() *durationpb.Duration {
	if x != nil {
		return x.HealthCheckPeriod
	}
	return nil
}

func (x *Data_PostgreSQL) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Data_PostgreSQL) GetPreparedStatementsEnabled() bool {
	if x != nil {
		return x.PreparedStatementsEnabled
	}
	return false
}

func (x *Data_PostgreSQL) GetTransaction() *Data_PostgreSQL_Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *Data_PostgreSQL) GetPoolMetricsEnabled() bool {
	if x != nil && x.PoolMetricsEnabled != nil {
		return *x.PoolMetricsEnabled
	}
	return false
}

// gRPC Client 配置（可选，用于服务间调用）
type Data_Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"` // 目标地址，留空则不创建 client
	Jwt           *Data_Client_JWT       `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	MetadataKeys  []string               `protobuf:"bytes,3,rep,name=metadata_keys,json=metadataKeys,proto3" json:"metadata_keys,omitempty"` // 转发到下游的 header 列表（默认同 server.metadata_keys）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Client) Reset() {
	*x = Data_Client{}
	mi := &file_configs_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Client) ProtoMessage() {}

func (x *Data_Client) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Client.ProtoReflect.Descriptor instead.
func (*Data_Client) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Client) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Data_Client) GetJwt() *Data_Client_JWT {
	if x != nil {
		return x.Jwt
	}
	return nil
}

func (x *Data_Client) GetMetadataKeys() []string {
	if x != nil {
		return x.MetadataKeys
	}
	return nil
}

type Data_PostgreSQL_Transaction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DefaultIsolation string                 `protobuf:"bytes,1,opt,name=default_isolation,json=defaultIsolation,proto3" json:"default_isolation,omitempty"`
	DefaultTimeout   *durationpb.Duration   `protobuf:"bytes,2,opt,name=default_timeout,json=defaultTimeout,proto3" json:"default_timeout,omitempty"`
	LockTimeout      *durationpb.Duration   `protobuf:"bytes,3,opt,name=lock_timeout,json=lockTimeout,proto3" json:"lock_timeout,omitempty"`
	MaxRetries       int32                  `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	MetricsEnabled   *bool                  `protobuf:"varint,5,opt,name=metrics_enabled,json=metricsEnabled,proto3,oneof" json:"metrics_enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Data_PostgreSQL_Transaction) Reset() {
	*x = Data_PostgreSQL_Transaction{}
	mi := &file_configs_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_PostgreSQL_Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_PostgreSQL_Transaction) ProtoMessage() {}

func (x *Data_PostgreSQL_Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_PostgreSQL_Transaction.ProtoReflect.Descriptor instead.
func (*Data_PostgreSQL_Transaction) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Data_PostgreSQL_Transaction) GetDefaultIsolation() string {
	if x != nil {
		return x.DefaultIsolation
	}
	return ""
}

func (x *Data_PostgreSQL_Transaction) GetDefaultTimeout() *durationpb.Duration {
	if x != nil {
		return x.DefaultTimeout
	}
	return nil
}

func (x *Data_PostgreSQL_Transaction) GetLockTimeout() *durationpb.Duration {
	if x != nil {
		return x.LockTimeout
	}
	return nil
}

func (x *Data_PostgreSQL_Transaction) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Data_PostgreSQL_Transaction) GetMetricsEnabled() bool {
	if x != nil && x.MetricsEnabled != nil {
		return *x.MetricsEnabled
	}
	return false
}

type Data_Client_JWT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audience      string                 `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	Disabled      bool                   `protobuf:"varint,2,opt,name=disabled,proto3" json:"disabled,omitempty"`
	HeaderKey     string                 `protobuf:"bytes,3,opt,name=header_key,json=headerKey,proto3" json:"header_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Client_JWT) Reset() {
	*x = Data_Client_JWT{}
	mi := &file_configs_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Client_JWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Client_JWT) ProtoMessage() {}

func (x *Data_Client_JWT) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Client_JWT.ProtoReflect.Descriptor instead.
func (*Data_Client_JWT) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{2, 1, 0}
}

func (x *Data_Client_JWT) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *Data_Client_JWT) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Data_Client_JWT) GetHeaderKey() string {
	if x != nil {
		return x.HeaderKey
	}
	return ""
}

type Observability_Tracing struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Enabled            bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Exporter           string                 `protobuf:"bytes,2,opt,name=exporter,proto3" json:"exporter,omitempty"`
	Endpoint           string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Headers            map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Insecure           bool                   `protobuf:"varint,5,opt,name=insecure,proto3" json:"insecure,omitempty"`
	SamplingRatio      float64                `protobuf:"fixed64,6,opt,name=sampling_ratio,json=samplingRatio,proto3" json:"sampling_ratio,omitempty"`
	BatchTimeout       *durationpb.Duration   `protobuf:"bytes,7,opt,name=batch_timeout,json=batchTimeout,proto3" json:"batch_timeout,omitempty"`
	ExportTimeout      *durationpb.Duration   `protobuf:"bytes,8,opt,name=export_timeout,json=exportTimeout,proto3" json:"export_timeout,omitempty"`
	MaxQueueSize       int32                  `protobuf:"varint,9,opt,name=max_queue_size,json=maxQueueSize,proto3" json:"max_queue_size,omitempty"`
	MaxExportBatchSize int32                  `protobuf:"varint,10,opt,name=max_export_batch_size,json=maxExportBatchSize,proto3" json:"max_export_batch_size,omitempty"`
	Required           bool                   `protobuf:"varint,11,opt,name=required,proto3" json:"required,omitempty"`
	ServiceName        string                 `protobuf:"bytes,12,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion     string                 `protobuf:"bytes,13,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	Environment        string                 `protobuf:"bytes,14,opt,name=environment,proto3" json:"environment,omitempty"`
	Attributes         map[string]string      `protobuf:"bytes,15,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Observability_Tracing) Reset() {
	*x = Observability_Tracing{}
	mi := &file_configs_conf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Tracing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Tracing) ProtoMessage() {}

func (x *Observability_Tracing) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Tracing.ProtoReflect.Descriptor instead.
func (*Observability_Tracing) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Observability_Tracing) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Observability_Tracing) GetExporter() string {
	if x != nil {
		return x.Exporter
	}
	return ""
}

func (x *Observability_Tracing) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Observability_Tracing) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Observability_Tracing) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *Observability_Tracing) GetSamplingRatio() float64 {
	if x != nil {
		return x.SamplingRatio
	}
	return 0
}

func (x *Observability_Tracing) GetBatchTimeout() *durationpb.Duration {
	if x != nil {
		return x.BatchTimeout
	}
	return nil
}

func (x *Observability_Tracing) GetExportTimeout() *durationpb.Duration {
	if x != nil {
		return x.ExportTimeout
	}
	return nil
}

func (x *Observability_Tracing) GetMaxQueueSize() int32 {
	if x != nil {
		return x.MaxQueueSize
	}
	return 0
}

func (x *Observability_Tracing) GetMaxExportBatchSize() int32 {
	if x != nil {
		return x.MaxExportBatchSize
	}
	return 0
}

func (x *Observability_Tracing) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Observability_Tracing) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Observability_Tracing) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *Observability_Tracing) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Observability_Tracing) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Observability_Metrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enabled             bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Exporter            string                 `protobuf:"bytes,2,opt,name=exporter,proto3" json:"exporter,omitempty"`
	Endpoint            string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Headers             map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Insecure            bool                   `protobuf:"varint,5,opt,name=insecure,proto3" json:"insecure,omitempty"`
	Interval            *durationpb.Duration   `protobuf:"bytes,6,opt,name=interval,proto3" json:"interval,omitempty"`
	DisableRuntimeStats bool                   `protobuf:"varint,7,opt,name=disable_runtime_stats,json=disableRuntimeStats,proto3" json:"disable_runtime_stats,omitempty"`
	Required            bool                   `protobuf:"varint,8,opt,name=required,proto3" json:"required,omitempty"`
	ResourceAttributes  map[string]string      `protobuf:"bytes,9,rep,name=resource_attributes,json=resourceAttributes,proto3" json:"resource_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GrpcEnabled         *bool                  `protobuf:"varint,10,opt,name=grpc_enabled,json=grpcEnabled,proto3,oneof" json:"grpc_enabled,omitempty"`
	GrpcIncludeHealth   *bool                  `protobuf:"varint,11,opt,name=grpc_include_health,json=grpcIncludeHealth,proto3,oneof" json:"grpc_include_health,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Observability_Metrics) Reset() {
	*x = Observability_Metrics{}
	mi := &file_configs_conf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Metrics) ProtoMessage() {}

func (x *Observability_Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Metrics.ProtoReflect.Descriptor instead.
func (*Observability_Metrics) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Observability_Metrics) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Observability_Metrics) GetExporter() string {
	if x != nil {
		return x.Exporter
	}
	return ""
}

func (x *Observability_Metrics) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Observability_Metrics) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Observability_Metrics) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *Observability_Metrics) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *Observability_Metrics) GetDisableRuntimeStats() bool {
	if x != nil {
		return x.DisableRuntimeStats
	}
	return false
}

func (x *Observability_Metrics) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Observability_Metrics) GetResourceAttributes() map[string]string {
	if x != nil {
		return x.ResourceAttributes
	}
	return nil
}

func (x *Observability_Metrics) GetGrpcEnabled() bool {
	if x != nil && x.GrpcEnabled != nil {
		return *x.GrpcEnabled
	}
	return false
}

func (x *Observability_Metrics) GetGrpcIncludeHealth() bool {
	if x != nil && x.GrpcIncludeHealth != nil {
		return *x.GrpcIncludeHealth
	}
	return false
}

var File_configs_conf_proto protoreflect.FileDescriptor

const file_configs_conf_proto_rawDesc = "" +
	"\n" +
	"\x12configs/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bbuf/validate/validate.proto\"\xd3\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12?\n" +
	"\robservability\x18\x03 \x01(\v2\x19.kratos.api.ObservabilityR\robservability\x123\n" +
	"\tmessaging\x18\x04 \x01(\v2\x15.kratos.api.MessagingR\tmessaging\"\x92\x05\n" +
	"\x06Server\x12+\n" +
	"\x04grpc\x18\x01 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x12(\n" +
	"\x03jwt\x18\x02 \x01(\v2\x16.kratos.api.Server.JWTR\x03jwt\x127\n" +
	"\bhandlers\x18\x03 \x01(\v2\x1b.kratos.api.Server.HandlersR\bhandlers\x12#\n" +
	"\rmetadata_keys\x18\x04 \x03(\tR\fmetadataKeys\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1a\x92\x01\n" +
	"\x03JWT\x12+\n" +
	"\x11expected_audience\x18\x01 \x01(\tR\x10expectedAudience\x12#\n" +
	"\rskip_validate\x18\x02 \x01(\bR\fskipValidate\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x1d\n" +
	"\n" +
	"header_key\x18\x04 \x01(\tR\theaderKey\x1a\xd2\x01\n" +
	"\bHandlers\x12B\n" +
	"\x0fdefault_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x0edefaultTimeout\x12B\n" +
	"\x0fcommand_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0ecommandTimeout\x12>\n" +
	"\rquery_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\fqueryTimeout\"\xe6\t\n" +
	"\x04Data\x12?\n" +
	"\bpostgres\x18\x01 \x01(\v2\x1b.kratos.api.Data.PostgreSQLB\x06\xbaH\x03\xc8\x01\x01R\bpostgres\x128\n" +
	"\vgrpc_client\x18\x02 \x01(\v2\x17.kratos.api.Data.ClientR\n" +
	"grpcClient\x1a\x8d\a\n" +
	"\n" +
	"PostgreSQL\x12.\n" +
	"\x03dsn\x18\x01 \x01(\tB\x1c\xbaH\x19r\x17\x10\x012\x13^postgres(ql)?://.*R\x03dsn\x12/\n" +
	"\x0emax_open_conns\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x01R\fmaxOpenConns\x12/\n" +
	"\x0emin_open_conns\x18\x03 \x01(\x05B\t\xbaH\x06\x1a\x04\x182(\x00R\fminOpenConns\x12E\n" +
	"\x11max_conn_lifetime\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x0fmaxConnLifetime\x12F\n" +
	"\x12max_conn_idle_time\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x0fmaxConnIdleTime\x12I\n" +
	"\x13health_check_period\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x11healthCheckPeriod\x12\x16\n" +
	"\x06schema\x18\a \x01(\tR\x06schema\x12>\n" +
	"\x1bprepared_statements_enabled\x18\b \x01(\bR\x19preparedStatementsEnabled\x12I\n" +
	"\vtransaction\x18\t \x01(\v2'.kratos.api.Data.PostgreSQL.TransactionR\vtransaction\x125\n" +
	"\x14pool_metrics_enabled\x18\n" +
	" \x01(\bH\x00R\x12poolMetricsEnabled\x88\x01\x01\x1a\x9f\x02\n" +
	"\vTransaction\x12+\n" +
	"\x11default_isolation\x18\x01 \x01(\tR\x10defaultIsolation\x12B\n" +
	"\x0fdefault_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0edefaultTimeout\x12<\n" +
	"\flock_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vlockTimeout\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries\x12,\n" +
	"\x0fmetrics_enabled\x18\x05 \x01(\bH\x00R\x0emetricsEnabled\x88\x01\x01B\x12\n" +
	"\x10_metrics_enabledB\x17\n" +
	"\x15_pool_metrics_enabled\x1a\xd2\x01\n" +
	"\x06Client\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12-\n" +
	"\x03jwt\x18\x02 \x01(\v2\x1b.kratos.api.Data.Client.JWTR\x03jwt\x12#\n" +
	"\rmetadata_keys\x18\x03 \x03(\tR\fmetadataKeys\x1a\\\n" +
	"\x03JWT\x12\x1a\n" +
	"\baudience\x18\x01 \x01(\tR\baudience\x12\x1a\n" +
	"\bdisabled\x18\x02 \x01(\bR\bdisabled\x12\x1d\n" +
	"\n" +
	"header_key\x18\x03 \x01(\tR\theaderKey\"\x8a\x0e\n" +
	"\rObservability\x12\\\n" +
	"\x11global_attributes\x18\x01 \x03(\v2/.kratos.api.Observability.GlobalAttributesEntryR\x10globalAttributes\x12;\n" +
	"\atracing\x18\x02 \x01(\v2!.kratos.api.Observability.TracingR\atracing\x12;\n" +
	"\ametrics\x18\x03 \x01(\v2!.kratos.api.Observability.MetricsR\ametrics\x1a\x9b\x06\n" +
	"\aTracing\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bexporter\x18\x02 \x01(\tR\bexporter\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12H\n" +
	"\aheaders\x18\x04 \x03(\v2..kratos.api.Observability.Tracing.HeadersEntryR\aheaders\x12\x1a\n" +
	"\binsecure\x18\x05 \x01(\bR\binsecure\x12%\n" +
	"\x0esampling_ratio\x18\x06 \x01(\x01R\rsamplingRatio\x12>\n" +
	"\rbatch_timeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\fbatchTimeout\x12@\n" +
	"\x0eexport_timeout\x18\b \x01(\v2\x19.google.protobuf.DurationR\rexportTimeout\x12$\n" +
	"\x0emax_queue_size\x18\t \x01(\x05R\fmaxQueueSize\x121\n" +
	"\x15max_export_batch_size\x18\n" +
	" \x01(\x05R\x12maxExportBatchSize\x12\x1a\n" +
	"\brequired\x18\v \x01(\bR\brequired\x12!\n" +
	"\fservice_name\x18\f \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_version\x18\r \x01(\tR\x0eserviceVersion\x12 \n" +
	"\venvironment\x18\x0e \x01(\tR\venvironment\x12Q\n" +
	"\n" +
	"attributes\x18\x0f \x03(\v21.kratos.api.Observability.Tracing.AttributesEntryR\n" +
	"attributes\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xbd\x05\n" +
	"\aMetrics\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bexporter\x18\x02 \x01(\tR\bexporter\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12H\n" +
	"\aheaders\x18\x04 \x03(\v2..kratos.api.Observability.Metrics.HeadersEntryR\aheaders\x12\x1a\n" +
	"\binsecure\x18\x05 \x01(\bR\binsecure\x125\n" +
	"\binterval\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\binterval\x122\n" +
	"\x15disable_runtime_stats\x18\a \x01(\bR\x13disableRuntimeStats\x12\x1a\n" +
	"\brequired\x18\b \x01(\bR\brequired\x12j\n" +
	"\x13resource_attributes\x18\t \x03(\v29.kratos.api.Observability.Metrics.ResourceAttributesEntryR\x12resourceAttributes\x12&\n" +
	"\fgrpc_enabled\x18\n" +
	" \x01(\bH\x00R\vgrpcEnabled\x88\x01\x01\x123\n" +
	"\x13grpc_include_health\x18\v \x01(\bH\x01R\x11grpcIncludeHealth\x88\x01\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\x17ResourceAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_grpc_enabledB\x16\n" +
	"\x14_grpc_include_health\x1aC\n" +
	"\x15GlobalAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x01\n" +
	"\tMessaging\x12*\n" +
	"\x06pubsub\x18\x01 \x01(\v2\x12.kratos.api.PubSubR\x06pubsub\x123\n" +
	"\x06outbox\x18\x02 \x01(\v2\x1b.kratos.api.OutboxPublisherR\x06outbox\x12/\n" +
	"\x05inbox\x18\x03 \x01(\v2\x19.kratos.api.InboxConsumerR\x05inbox\x122\n" +
	"\n" +
	"engagement\x18\x04 \x01(\v2\x12.kratos.api.PubSubR\n" +
	"engagement\"\xf4\x03\n" +
	"\x06PubSub\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\tR\atopicId\x12'\n" +
	"\x0fsubscription_id\x18\x03 \x01(\tR\x0esubscriptionId\x120\n" +
	"\x14ordering_key_enabled\x18\x04 \x01(\bR\x12orderingKeyEnabled\x12'\n" +
	"\x0flogging_enabled\x18\x05 \x01(\bR\x0eloggingEnabled\x12'\n" +
	"\x0fmetrics_enabled\x18\x06 \x01(\bR\x0emetricsEnabled\x12+\n" +
	"\x11emulator_endpoint\x18\a \x01(\tR\x10emulatorEndpoint\x12B\n" +
	"\x0fpublish_timeout\x18\b \x01(\v2\x19.google.protobuf.DurationR\x0epublishTimeout\x12-\n" +
	"\areceive\x18\t \x01(\v2\x13.kratos.api.ReceiveR\areceive\x122\n" +
	"\x15exactly_once_delivery\x18\n" +
	" \x01(\bR\x13exactlyOnceDelivery\x12/\n" +
	"\x14dead_letter_topic_id\x18\v \x01(\tR\x11deadLetterTopicId\"\xab\x02\n" +
	"\aReceive\x12%\n" +
	"\x0enum_goroutines\x18\x01 \x01(\x05R\rnumGoroutines\x128\n" +
	"\x18max_outstanding_messages\x18\x02 \x01(\x05R\x16maxOutstandingMessages\x122\n" +
	"\x15max_outstanding_bytes\x18\x03 \x01(\x05R\x13maxOutstandingBytes\x12>\n" +
	"\rmax_extension\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fmaxExtension\x12K\n" +
	"\x14max_extension_period\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x12maxExtensionPeriod\"\xab\x04\n" +
	"\x0fOutboxPublisher\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x01 \x01(\x05R\tbatchSize\x12>\n" +
	"\rtick_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\ftickInterval\x12B\n" +
	"\x0finitial_backoff\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0einitialBackoff\x12:\n" +
	"\vmax_backoff\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"maxBackoff\x12!\n" +
	"\fmax_attempts\x18\x05 \x01(\x05R\vmaxAttempts\x12B\n" +
	"\x0fpublish_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x0epublishTimeout\x12\x18\n" +
	"\aworkers\x18\a \x01(\x05R\aworkers\x124\n" +
	"\block_ttl\x18\b \x01(\v2\x19.google.protobuf.DurationR\alockTtl\x12,\n" +
	"\x0flogging_enabled\x18\t \x01(\bH\x00R\x0eloggingEnabled\x88\x01\x01\x12,\n" +
	"\x0fmetrics_enabled\x18\n" +
	" \x01(\bH\x01R\x0emetricsEnabled\x88\x01\x01B\x12\n" +
	"\x10_logging_enabledB\x12\n" +
	"\x10_metrics_enabled\"\xe3\x01\n" +
	"\rInboxConsumer\x12%\n" +
	"\x0esource_service\x18\x01 \x01(\tR\rsourceService\x12'\n" +
	"\x0fmax_concurrency\x18\x02 \x01(\x05R\x0emaxConcurrency\x12,\n" +
	"\x0flogging_enabled\x18\x03 \x01(\bH\x00R\x0eloggingEnabled\x88\x01\x01\x12,\n" +
	"\x0fmetrics_enabled\x18\x04 \x01(\bH\x01R\x0emetricsEnabled\x88\x01\x01B\x12\n" +
	"\x10_logging_enabledB\x12\n" +
	"\x10_metrics_enabledB@Z>github.com/bionicotaku/lingo-services-profile/configs;configpbb\x06proto3"

var (
	file_configs_conf_proto_rawDescOnce sync.Once
	file_configs_conf_proto_rawDescData []byte
)

func file_configs_conf_proto_rawDescGZIP() []byte {
	file_configs_conf_proto_rawDescOnce.Do(func() {
		file_configs_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configs_conf_proto_rawDesc), len(file_configs_conf_proto_rawDesc)))
	})
	return file_configs_conf_proto_rawDescData
}

var file_configs_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_configs_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),                   // 0: kratos.api.Bootstrap
	(*Server)(nil),                      // 1: kratos.api.Server
	(*Data)(nil),                        // 2: kratos.api.Data
	(*Observability)(nil),               // 3: kratos.api.Observability
	(*Messaging)(nil),                   // 4: kratos.api.Messaging
	(*PubSub)(nil),                      // 5: kratos.api.PubSub
	(*Receive)(nil),                     // 6: kratos.api.Receive
	(*OutboxPublisher)(nil),             // 7: kratos.api.OutboxPublisher
	(*InboxConsumer)(nil),               // 8: kratos.api.InboxConsumer
	(*Server_GRPC)(nil),                 // 9: kratos.api.Server.GRPC
	(*Server_JWT)(nil),                  // 10: kratos.api.Server.JWT
	(*Server_Handlers)(nil),             // 11: kratos.api.Server.Handlers
	(*Data_PostgreSQL)(nil),             // 12: kratos.api.Data.PostgreSQL
	(*Data_Client)(nil),                 // 13: kratos.api.Data.Client
	(*Data_PostgreSQL_Transaction)(nil), // 14: kratos.api.Data.PostgreSQL.Transaction
	(*Data_Client_JWT)(nil),             // 15: kratos.api.Data.Client.JWT
	(*Observability_Tracing)(nil),       // 16: kratos.api.Observability.Tracing
	(*Observability_Metrics)(nil),       // 17: kratos.api.Observability.Metrics
	nil,                                 // 18: kratos.api.Observability.GlobalAttributesEntry
	nil,                                 // 19: kratos.api.Observability.Tracing.HeadersEntry
	nil,                                 // 20: kratos.api.Observability.Tracing.AttributesEntry
	nil,                                 // 21: kratos.api.Observability.Metrics.HeadersEntry
	nil,                                 // 22: kratos.api.Observability.Metrics.ResourceAttributesEntry
	(*durationpb.Duration)(nil),         // 23: google.protobuf.Duration
}
var file_configs_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Bootstrap.observability:type_name -> kratos.api.Observability
	4,  // 3: kratos.api.Bootstrap.messaging:type_name -> kratos.api.Messaging
	9,  // 4: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	10, // 5: kratos.api.Server.jwt:type_name -> kratos.api.Server.JWT
	11, // 6: kratos.api.Server.handlers:type_name -> kratos.api.Server.Handlers
	12, // 7: kratos.api.Data.postgres:type_name -> kratos.api.Data.PostgreSQL
	13, // 8: kratos.api.Data.grpc_client:type_name -> kratos.api.Data.Client
	18, // 9: kratos.api.Observability.global_attributes:type_name -> kratos.api.Observability.GlobalAttributesEntry
	16, // 10: kratos.api.Observability.tracing:type_name -> kratos.api.Observability.Tracing
	17, // 11: kratos.api.Observability.metrics:type_name -> kratos.api.Observability.Metrics
	5,  // 12: kratos.api.Messaging.pubsub:type_name -> kratos.api.PubSub
	7,  // 13: kratos.api.Messaging.outbox:type_name -> kratos.api.OutboxPublisher
	8,  // 14: kratos.api.Messaging.inbox:type_name -> kratos.api.InboxConsumer
	5,  // 15: kratos.api.Messaging.engagement:type_name -> kratos.api.PubSub
	23, // 16: kratos.api.PubSub.publish_timeout:type_name -> google.protobuf.Duration
	6,  // 17: kratos.api.PubSub.receive:type_name -> kratos.api.Receive
	23, // 18: kratos.api.Receive.max_extension:type_name -> google.protobuf.Duration
	23, // 19: kratos.api.Receive.max_extension_period:type_name -> google.protobuf.Duration
	23, // 20: kratos.api.OutboxPublisher.tick_interval:type_name -> google.protobuf.Duration
	23, // 21: kratos.api.OutboxPublisher.initial_backoff:type_name -> google.protobuf.Duration
	23, // 22: kratos.api.OutboxPublisher.max_backoff:type_name -> google.protobuf.Duration
	23, // 23: kratos.api.OutboxPublisher.publish_timeout:type_name -> google.protobuf.Duration
	23, // 24: kratos.api.OutboxPublisher.lock_ttl:type_name -> google.protobuf.Duration
	23, // 25: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	23, // 26: kratos.api.Server.Handlers.default_timeout:type_name -> google.protobuf.Duration
	23, // 27: kratos.api.Server.Handlers.command_timeout:type_name -> google.protobuf.Duration
	23, // 28: kratos.api.Server.Handlers.query_timeout:type_name -> google.protobuf.Duration
	23, // 29: kratos.api.Data.PostgreSQL.max_conn_lifetime:type_name -> google.protobuf.Duration
	23, // 30: kratos.api.Data.PostgreSQL.max_conn_idle_time:type_name -> google.protobuf.Duration
	23, // 31: kratos.api.Data.PostgreSQL.health_check_period:type_name -> google.protobuf.Duration
	14, // 32: kratos.api.Data.PostgreSQL.transaction:type_name -> kratos.api.Data.PostgreSQL.Transaction
	15, // 33: kratos.api.Data.Client.jwt:type_name -> kratos.api.Data.Client.JWT
	23, // 34: kratos.api.Data.PostgreSQL.Transaction.default_timeout:type_name -> google.protobuf.Duration
	23, // 35: kratos.api.Data.PostgreSQL.Transaction.lock_timeout:type_name -> google.protobuf.Duration
	19, // 36: kratos.api.Observability.Tracing.headers:type_name -> kratos.api.Observability.Tracing.HeadersEntry
	23, // 37: kratos.api.Observability.Tracing.batch_timeout:type_name -> google.protobuf.Duration
	23, // 38: kratos.api.Observability.Tracing.export_timeout:type_name -> google.protobuf.Duration
	20, // 39: kratos.api.Observability.Tracing.attributes:type_name -> kratos.api.Observability.Tracing.AttributesEntry
	21, // 40: kratos.api.Observability.Metrics.headers:type_name -> kratos.api.Observability.Metrics.HeadersEntry
	23, // 41: kratos.api.Observability.Metrics.interval:type_name -> google.protobuf.Duration
	22, // 42: kratos.api.Observability.Metrics.resource_attributes:type_name -> kratos.api.Observability.Metrics.ResourceAttributesEntry
	43, // [43:43] is the sub-list for method output_type
	43, // [43:43] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_configs_conf_proto_init() }
func file_configs_conf_proto_init() {
	if File_configs_conf_proto != nil {
		return
	}
	file_configs_conf_proto_msgTypes[7].OneofWrappers = []any{}
	file_configs_conf_proto_msgTypes[8].OneofWrappers = []any{}
	file_configs_conf_proto_msgTypes[12].OneofWrappers = []any{}
	file_configs_conf_proto_msgTypes[14].OneofWrappers = []any{}
	file_configs_conf_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configs_conf_proto_rawDesc), len(file_configs_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configs_conf_proto_goTypes,
		DependencyIndexes: file_configs_conf_proto_depIdxs,
		MessageInfos:      file_configs_conf_proto_msgTypes,
	}.Build()
	File_configs_conf_proto = out.File
	file_configs_conf_proto_goTypes = nil
	file_configs_conf_proto_depIdxs = nil
}
