// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bionicotaku/lingo-services-profile/internal/services (interfaces: ProfileUsersRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	po "github.com/bionicotaku/lingo-services-profile/internal/models/po"
	repositories "github.com/bionicotaku/lingo-services-profile/internal/repositories"
	txmanager "github.com/bionicotaku/lingo-utils/txmanager"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockProfileUsersRepository is a mock of ProfileUsersRepository interface.
type MockProfileUsersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProfileUsersRepositoryMockRecorder
}

// MockProfileUsersRepositoryMockRecorder is the mock recorder for MockProfileUsersRepository.
type MockProfileUsersRepositoryMockRecorder struct {
	mock *MockProfileUsersRepository
}

// NewMockProfileUsersRepository creates a new mock instance.
func NewMockProfileUsersRepository(ctrl *gomock.Controller) *MockProfileUsersRepository {
	mock := &MockProfileUsersRepository{ctrl: ctrl}
	mock.recorder = &MockProfileUsersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileUsersRepository) EXPECT() *MockProfileUsersRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockProfileUsersRepository) Get(arg0 context.Context, arg1 txmanager.Session, arg2 uuid.UUID) (*po.ProfileUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*po.ProfileUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProfileUsersRepositoryMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProfileUsersRepository)(nil).Get), arg0, arg1, arg2)
}

// Upsert mocks base method.
func (m *MockProfileUsersRepository) Upsert(arg0 context.Context, arg1 txmanager.Session, arg2 repositories.UpsertProfileUserInput) (*po.ProfileUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1, arg2)
	ret0, _ := ret[0].(*po.ProfileUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockProfileUsersRepositoryMockRecorder) Upsert(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockProfileUsersRepository)(nil).Upsert), arg0, arg1, arg2)
}
