// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bionicotaku/lingo-services-profile/internal/services (interfaces: WatchLogsRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	po "github.com/bionicotaku/lingo-services-profile/internal/models/po"
	repositories "github.com/bionicotaku/lingo-services-profile/internal/repositories"
	txmanager "github.com/bionicotaku/lingo-utils/txmanager"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockWatchLogsRepository is a mock of WatchLogsRepository interface.
type MockWatchLogsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWatchLogsRepositoryMockRecorder
}

// MockWatchLogsRepositoryMockRecorder is the mock recorder for MockWatchLogsRepository.
type MockWatchLogsRepositoryMockRecorder struct {
	mock *MockWatchLogsRepository
}

// NewMockWatchLogsRepository creates a new mock instance.
func NewMockWatchLogsRepository(ctrl *gomock.Controller) *MockWatchLogsRepository {
	mock := &MockWatchLogsRepository{ctrl: ctrl}
	mock.recorder = &MockWatchLogsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatchLogsRepository) EXPECT() *MockWatchLogsRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockWatchLogsRepository) Get(arg0 context.Context, arg1 txmanager.Session, arg2, arg3 uuid.UUID) (*po.ProfileWatchLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*po.ProfileWatchLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWatchLogsRepositoryMockRecorder) Get(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWatchLogsRepository)(nil).Get), arg0, arg1, arg2, arg3)
}

// ListByUser mocks base method.
func (m *MockWatchLogsRepository) ListByUser(arg0 context.Context, arg1 txmanager.Session, arg2 uuid.UUID, arg3 bool, arg4, arg5 int32) ([]*po.ProfileWatchLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].([]*po.ProfileWatchLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockWatchLogsRepositoryMockRecorder) ListByUser(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockWatchLogsRepository)(nil).ListByUser), arg0, arg1, arg2, arg3, arg4, arg5)
}

// Upsert mocks base method.
func (m *MockWatchLogsRepository) Upsert(arg0 context.Context, arg1 txmanager.Session, arg2 repositories.UpsertWatchLogInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockWatchLogsRepositoryMockRecorder) Upsert(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockWatchLogsRepository)(nil).Upsert), arg0, arg1, arg2)
}
