// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bionicotaku/lingo-services-profile/internal/services (interfaces: VideoProjectionRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	po "github.com/bionicotaku/lingo-services-profile/internal/models/po"
	repositories "github.com/bionicotaku/lingo-services-profile/internal/repositories"
	txmanager "github.com/bionicotaku/lingo-utils/txmanager"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockVideoProjectionRepository is a mock of VideoProjectionRepository interface.
type MockVideoProjectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVideoProjectionRepositoryMockRecorder
}

// MockVideoProjectionRepositoryMockRecorder is the mock recorder for MockVideoProjectionRepository.
type MockVideoProjectionRepositoryMockRecorder struct {
	mock *MockVideoProjectionRepository
}

// NewMockVideoProjectionRepository creates a new mock instance.
func NewMockVideoProjectionRepository(ctrl *gomock.Controller) *MockVideoProjectionRepository {
	mock := &MockVideoProjectionRepository{ctrl: ctrl}
	mock.recorder = &MockVideoProjectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoProjectionRepository) EXPECT() *MockVideoProjectionRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockVideoProjectionRepository) Get(arg0 context.Context, arg1 txmanager.Session, arg2 uuid.UUID) (*po.ProfileVideoProjection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*po.ProfileVideoProjection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVideoProjectionRepositoryMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVideoProjectionRepository)(nil).Get), arg0, arg1, arg2)
}

// ListByIDs mocks base method.
func (m *MockVideoProjectionRepository) ListByIDs(arg0 context.Context, arg1 txmanager.Session, arg2 []uuid.UUID) ([]*po.ProfileVideoProjection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*po.ProfileVideoProjection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDs indicates an expected call of ListByIDs.
func (mr *MockVideoProjectionRepositoryMockRecorder) ListByIDs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDs", reflect.TypeOf((*MockVideoProjectionRepository)(nil).ListByIDs), arg0, arg1, arg2)
}

// Upsert mocks base method.
func (m *MockVideoProjectionRepository) Upsert(arg0 context.Context, arg1 txmanager.Session, arg2 repositories.UpsertVideoProjectionInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockVideoProjectionRepositoryMockRecorder) Upsert(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockVideoProjectionRepository)(nil).Upsert), arg0, arg1, arg2)
}
