// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package catalogsql

import (
	"database/sql/driver"
	"fmt"

	po "github.com/bionicotaku/lingo-services-catalog/internal/models/po"
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogStageStatus string

const (
	CatalogStageStatusPending    CatalogStageStatus = "pending"
	CatalogStageStatusProcessing CatalogStageStatus = "processing"
	CatalogStageStatusReady      CatalogStageStatus = "ready"
	CatalogStageStatusFailed     CatalogStageStatus = "failed"
)

func (e *CatalogStageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogStageStatus(s)
	case string:
		*e = CatalogStageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogStageStatus: %T", src)
	}
	return nil
}

type NullCatalogStageStatus struct {
	CatalogStageStatus CatalogStageStatus `json:"catalog_stage_status"`
	Valid              bool               `json:"valid"` // Valid is true if CatalogStageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogStageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogStageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogStageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogStageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogStageStatus), nil
}

type CatalogVideoStatus string

const (
	CatalogVideoStatusPendingUpload CatalogVideoStatus = "pending_upload"
	CatalogVideoStatusProcessing    CatalogVideoStatus = "processing"
	CatalogVideoStatusReady         CatalogVideoStatus = "ready"
	CatalogVideoStatusPublished     CatalogVideoStatus = "published"
	CatalogVideoStatusFailed        CatalogVideoStatus = "failed"
	CatalogVideoStatusRejected      CatalogVideoStatus = "rejected"
	CatalogVideoStatusArchived      CatalogVideoStatus = "archived"
)

func (e *CatalogVideoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogVideoStatus(s)
	case string:
		*e = CatalogVideoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogVideoStatus: %T", src)
	}
	return nil
}

type NullCatalogVideoStatus struct {
	CatalogVideoStatus CatalogVideoStatus `json:"catalog_video_status"`
	Valid              bool               `json:"valid"` // Valid is true if CatalogVideoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogVideoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogVideoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogVideoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogVideoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogVideoStatus), nil
}

type CatalogVideo struct {
	VideoID           uuid.UUID          `json:"video_id"`
	UploadUserID      uuid.UUID          `json:"upload_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	RawFileReference  string             `json:"raw_file_reference"`
	Status            po.VideoStatus     `json:"status"`
	Version           int64              `json:"version"`
	MediaStatus       po.StageStatus     `json:"media_status"`
	AnalysisStatus    po.StageStatus     `json:"analysis_status"`
	MediaJobID        pgtype.Text        `json:"media_job_id"`
	MediaEmittedAt    pgtype.Timestamptz `json:"media_emitted_at"`
	AnalysisJobID     pgtype.Text        `json:"analysis_job_id"`
	AnalysisEmittedAt pgtype.Timestamptz `json:"analysis_emitted_at"`
	RawFileSize       pgtype.Int8        `json:"raw_file_size"`
	RawResolution     pgtype.Text        `json:"raw_resolution"`
	RawBitrate        pgtype.Int4        `json:"raw_bitrate"`
	DurationMicros    pgtype.Int8        `json:"duration_micros"`
	EncodedResolution pgtype.Text        `json:"encoded_resolution"`
	EncodedBitrate    pgtype.Int4        `json:"encoded_bitrate"`
	ThumbnailUrl      pgtype.Text        `json:"thumbnail_url"`
	HlsMasterPlaylist pgtype.Text        `json:"hls_master_playlist"`
	Difficulty        pgtype.Text        `json:"difficulty"`
	Summary           pgtype.Text        `json:"summary"`
	Tags              []string           `json:"tags"`
	VisibilityStatus  string             `json:"visibility_status"`
	PublishAt         pgtype.Timestamptz `json:"publish_at"`
	RawSubtitleUrl    pgtype.Text        `json:"raw_subtitle_url"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
}

type CatalogVideoUserEngagementsProjection struct {
	UserID               uuid.UUID          `json:"user_id"`
	VideoID              uuid.UUID          `json:"video_id"`
	HasLiked             bool               `json:"has_liked"`
	HasBookmarked        bool               `json:"has_bookmarked"`
	LikedOccurredAt      pgtype.Timestamptz `json:"liked_occurred_at"`
	BookmarkedOccurredAt pgtype.Timestamptz `json:"bookmarked_occurred_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
